// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AllSymbolgroupinfo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_AllSymbolgroupinfo_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_AllSymbolgroupinfo_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_AllSymbolgroupinfo_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_AllSymbolgroupinfo_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_AllSymbolgroupinfo_2eproto;
namespace Oreka {
class AllSymbolgroupinfo;
struct AllSymbolgroupinfoDefaultTypeInternal;
extern AllSymbolgroupinfoDefaultTypeInternal _AllSymbolgroupinfo_default_instance_;
class AllSymbolgroupinfo_Symbolgroups;
struct AllSymbolgroupinfo_SymbolgroupsDefaultTypeInternal;
extern AllSymbolgroupinfo_SymbolgroupsDefaultTypeInternal _AllSymbolgroupinfo_Symbolgroups_default_instance_;
}  // namespace Oreka
PROTOBUF_NAMESPACE_OPEN
template <>
::Oreka::AllSymbolgroupinfo* Arena::CreateMaybeMessage<::Oreka::AllSymbolgroupinfo>(Arena*);
template <>
::Oreka::AllSymbolgroupinfo_Symbolgroups* Arena::CreateMaybeMessage<::Oreka::AllSymbolgroupinfo_Symbolgroups>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace Oreka {

// ===================================================================


// -------------------------------------------------------------------

class AllSymbolgroupinfo_Symbolgroups final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Oreka.AllSymbolgroupinfo.Symbolgroups) */ {
 public:
  inline AllSymbolgroupinfo_Symbolgroups() : AllSymbolgroupinfo_Symbolgroups(nullptr) {}
  ~AllSymbolgroupinfo_Symbolgroups() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AllSymbolgroupinfo_Symbolgroups(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AllSymbolgroupinfo_Symbolgroups(const AllSymbolgroupinfo_Symbolgroups& from);
  AllSymbolgroupinfo_Symbolgroups(AllSymbolgroupinfo_Symbolgroups&& from) noexcept
    : AllSymbolgroupinfo_Symbolgroups() {
    *this = ::std::move(from);
  }

  inline AllSymbolgroupinfo_Symbolgroups& operator=(const AllSymbolgroupinfo_Symbolgroups& from) {
    CopyFrom(from);
    return *this;
  }
  inline AllSymbolgroupinfo_Symbolgroups& operator=(AllSymbolgroupinfo_Symbolgroups&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AllSymbolgroupinfo_Symbolgroups& default_instance() {
    return *internal_default_instance();
  }
  static inline const AllSymbolgroupinfo_Symbolgroups* internal_default_instance() {
    return reinterpret_cast<const AllSymbolgroupinfo_Symbolgroups*>(
               &_AllSymbolgroupinfo_Symbolgroups_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AllSymbolgroupinfo_Symbolgroups& a, AllSymbolgroupinfo_Symbolgroups& b) {
    a.Swap(&b);
  }
  inline void Swap(AllSymbolgroupinfo_Symbolgroups* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AllSymbolgroupinfo_Symbolgroups* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AllSymbolgroupinfo_Symbolgroups* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AllSymbolgroupinfo_Symbolgroups>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AllSymbolgroupinfo_Symbolgroups& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AllSymbolgroupinfo_Symbolgroups& from) {
    AllSymbolgroupinfo_Symbolgroups::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AllSymbolgroupinfo_Symbolgroups* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Oreka.AllSymbolgroupinfo.Symbolgroups";
  }
  protected:
  explicit AllSymbolgroupinfo_Symbolgroups(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSymbolgroupFieldNumber = 1,
    kSymbolgroupmarginFieldNumber = 2,
  };
  // string symbolgroup = 1;
  void clear_symbolgroup() ;
  const std::string& symbolgroup() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_symbolgroup(Arg_&& arg, Args_... args);
  std::string* mutable_symbolgroup();
  PROTOBUF_NODISCARD std::string* release_symbolgroup();
  void set_allocated_symbolgroup(std::string* ptr);

  private:
  const std::string& _internal_symbolgroup() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_symbolgroup(
      const std::string& value);
  std::string* _internal_mutable_symbolgroup();

  public:
  // double symbolgroupmargin = 2;
  void clear_symbolgroupmargin() ;
  double symbolgroupmargin() const;
  void set_symbolgroupmargin(double value);

  private:
  double _internal_symbolgroupmargin() const;
  void _internal_set_symbolgroupmargin(double value);

  public:
  // @@protoc_insertion_point(class_scope:Oreka.AllSymbolgroupinfo.Symbolgroups)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr symbolgroup_;
    double symbolgroupmargin_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AllSymbolgroupinfo_2eproto;
};// -------------------------------------------------------------------

class AllSymbolgroupinfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Oreka.AllSymbolgroupinfo) */ {
 public:
  inline AllSymbolgroupinfo() : AllSymbolgroupinfo(nullptr) {}
  ~AllSymbolgroupinfo() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AllSymbolgroupinfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AllSymbolgroupinfo(const AllSymbolgroupinfo& from);
  AllSymbolgroupinfo(AllSymbolgroupinfo&& from) noexcept
    : AllSymbolgroupinfo() {
    *this = ::std::move(from);
  }

  inline AllSymbolgroupinfo& operator=(const AllSymbolgroupinfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline AllSymbolgroupinfo& operator=(AllSymbolgroupinfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AllSymbolgroupinfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const AllSymbolgroupinfo* internal_default_instance() {
    return reinterpret_cast<const AllSymbolgroupinfo*>(
               &_AllSymbolgroupinfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AllSymbolgroupinfo& a, AllSymbolgroupinfo& b) {
    a.Swap(&b);
  }
  inline void Swap(AllSymbolgroupinfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AllSymbolgroupinfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AllSymbolgroupinfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AllSymbolgroupinfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AllSymbolgroupinfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AllSymbolgroupinfo& from) {
    AllSymbolgroupinfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AllSymbolgroupinfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Oreka.AllSymbolgroupinfo";
  }
  protected:
  explicit AllSymbolgroupinfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef AllSymbolgroupinfo_Symbolgroups Symbolgroups;

  // accessors -------------------------------------------------------

  enum : int {
    kSymbolgroupsFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // repeated .Oreka.AllSymbolgroupinfo.Symbolgroups symbolgroups = 2;
  int symbolgroups_size() const;
  private:
  int _internal_symbolgroups_size() const;

  public:
  void clear_symbolgroups() ;
  ::Oreka::AllSymbolgroupinfo_Symbolgroups* mutable_symbolgroups(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::AllSymbolgroupinfo_Symbolgroups >*
      mutable_symbolgroups();
  private:
  const ::Oreka::AllSymbolgroupinfo_Symbolgroups& _internal_symbolgroups(int index) const;
  ::Oreka::AllSymbolgroupinfo_Symbolgroups* _internal_add_symbolgroups();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::AllSymbolgroupinfo_Symbolgroups>& _internal_symbolgroups() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::AllSymbolgroupinfo_Symbolgroups>* _internal_mutable_symbolgroups();
  public:
  const ::Oreka::AllSymbolgroupinfo_Symbolgroups& symbolgroups(int index) const;
  ::Oreka::AllSymbolgroupinfo_Symbolgroups* add_symbolgroups();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::AllSymbolgroupinfo_Symbolgroups >&
      symbolgroups() const;
  // string type = 1;
  void clear_type() ;
  const std::string& type() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* ptr);

  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(
      const std::string& value);
  std::string* _internal_mutable_type();

  public:
  // @@protoc_insertion_point(class_scope:Oreka.AllSymbolgroupinfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::AllSymbolgroupinfo_Symbolgroups > symbolgroups_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AllSymbolgroupinfo_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AllSymbolgroupinfo_Symbolgroups

// string symbolgroup = 1;
inline void AllSymbolgroupinfo_Symbolgroups::clear_symbolgroup() {
  _impl_.symbolgroup_.ClearToEmpty();
}
inline const std::string& AllSymbolgroupinfo_Symbolgroups::symbolgroup() const {
  // @@protoc_insertion_point(field_get:Oreka.AllSymbolgroupinfo.Symbolgroups.symbolgroup)
  return _internal_symbolgroup();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AllSymbolgroupinfo_Symbolgroups::set_symbolgroup(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.symbolgroup_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.AllSymbolgroupinfo.Symbolgroups.symbolgroup)
}
inline std::string* AllSymbolgroupinfo_Symbolgroups::mutable_symbolgroup() {
  std::string* _s = _internal_mutable_symbolgroup();
  // @@protoc_insertion_point(field_mutable:Oreka.AllSymbolgroupinfo.Symbolgroups.symbolgroup)
  return _s;
}
inline const std::string& AllSymbolgroupinfo_Symbolgroups::_internal_symbolgroup() const {
  return _impl_.symbolgroup_.Get();
}
inline void AllSymbolgroupinfo_Symbolgroups::_internal_set_symbolgroup(const std::string& value) {
  ;


  _impl_.symbolgroup_.Set(value, GetArenaForAllocation());
}
inline std::string* AllSymbolgroupinfo_Symbolgroups::_internal_mutable_symbolgroup() {
  ;
  return _impl_.symbolgroup_.Mutable( GetArenaForAllocation());
}
inline std::string* AllSymbolgroupinfo_Symbolgroups::release_symbolgroup() {
  // @@protoc_insertion_point(field_release:Oreka.AllSymbolgroupinfo.Symbolgroups.symbolgroup)
  return _impl_.symbolgroup_.Release();
}
inline void AllSymbolgroupinfo_Symbolgroups::set_allocated_symbolgroup(std::string* value) {
  _impl_.symbolgroup_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.symbolgroup_.IsDefault()) {
          _impl_.symbolgroup_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.AllSymbolgroupinfo.Symbolgroups.symbolgroup)
}

// double symbolgroupmargin = 2;
inline void AllSymbolgroupinfo_Symbolgroups::clear_symbolgroupmargin() {
  _impl_.symbolgroupmargin_ = 0;
}
inline double AllSymbolgroupinfo_Symbolgroups::symbolgroupmargin() const {
  // @@protoc_insertion_point(field_get:Oreka.AllSymbolgroupinfo.Symbolgroups.symbolgroupmargin)
  return _internal_symbolgroupmargin();
}
inline void AllSymbolgroupinfo_Symbolgroups::set_symbolgroupmargin(double value) {
  _internal_set_symbolgroupmargin(value);
  // @@protoc_insertion_point(field_set:Oreka.AllSymbolgroupinfo.Symbolgroups.symbolgroupmargin)
}
inline double AllSymbolgroupinfo_Symbolgroups::_internal_symbolgroupmargin() const {
  return _impl_.symbolgroupmargin_;
}
inline void AllSymbolgroupinfo_Symbolgroups::_internal_set_symbolgroupmargin(double value) {
  ;
  _impl_.symbolgroupmargin_ = value;
}

// -------------------------------------------------------------------

// AllSymbolgroupinfo

// string type = 1;
inline void AllSymbolgroupinfo::clear_type() {
  _impl_.type_.ClearToEmpty();
}
inline const std::string& AllSymbolgroupinfo::type() const {
  // @@protoc_insertion_point(field_get:Oreka.AllSymbolgroupinfo.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AllSymbolgroupinfo::set_type(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.AllSymbolgroupinfo.type)
}
inline std::string* AllSymbolgroupinfo::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:Oreka.AllSymbolgroupinfo.type)
  return _s;
}
inline const std::string& AllSymbolgroupinfo::_internal_type() const {
  return _impl_.type_.Get();
}
inline void AllSymbolgroupinfo::_internal_set_type(const std::string& value) {
  ;


  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* AllSymbolgroupinfo::_internal_mutable_type() {
  ;
  return _impl_.type_.Mutable( GetArenaForAllocation());
}
inline std::string* AllSymbolgroupinfo::release_type() {
  // @@protoc_insertion_point(field_release:Oreka.AllSymbolgroupinfo.type)
  return _impl_.type_.Release();
}
inline void AllSymbolgroupinfo::set_allocated_type(std::string* value) {
  _impl_.type_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.type_.IsDefault()) {
          _impl_.type_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.AllSymbolgroupinfo.type)
}

// repeated .Oreka.AllSymbolgroupinfo.Symbolgroups symbolgroups = 2;
inline int AllSymbolgroupinfo::_internal_symbolgroups_size() const {
  return _impl_.symbolgroups_.size();
}
inline int AllSymbolgroupinfo::symbolgroups_size() const {
  return _internal_symbolgroups_size();
}
inline void AllSymbolgroupinfo::clear_symbolgroups() {
  _internal_mutable_symbolgroups()->Clear();
}
inline ::Oreka::AllSymbolgroupinfo_Symbolgroups* AllSymbolgroupinfo::mutable_symbolgroups(int index) {
  // @@protoc_insertion_point(field_mutable:Oreka.AllSymbolgroupinfo.symbolgroups)
  return _internal_mutable_symbolgroups()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::AllSymbolgroupinfo_Symbolgroups >*
AllSymbolgroupinfo::mutable_symbolgroups() {
  // @@protoc_insertion_point(field_mutable_list:Oreka.AllSymbolgroupinfo.symbolgroups)
  return _internal_mutable_symbolgroups();
}
inline const ::Oreka::AllSymbolgroupinfo_Symbolgroups& AllSymbolgroupinfo::_internal_symbolgroups(int index) const {
  return _internal_symbolgroups().Get(index);
}
inline const ::Oreka::AllSymbolgroupinfo_Symbolgroups& AllSymbolgroupinfo::symbolgroups(int index) const {
  // @@protoc_insertion_point(field_get:Oreka.AllSymbolgroupinfo.symbolgroups)
  return _internal_symbolgroups(index);
}
inline ::Oreka::AllSymbolgroupinfo_Symbolgroups* AllSymbolgroupinfo::_internal_add_symbolgroups() {
  return _internal_mutable_symbolgroups()->Add();
}
inline ::Oreka::AllSymbolgroupinfo_Symbolgroups* AllSymbolgroupinfo::add_symbolgroups() {
  ::Oreka::AllSymbolgroupinfo_Symbolgroups* _add = _internal_add_symbolgroups();
  // @@protoc_insertion_point(field_add:Oreka.AllSymbolgroupinfo.symbolgroups)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::AllSymbolgroupinfo_Symbolgroups >&
AllSymbolgroupinfo::symbolgroups() const {
  // @@protoc_insertion_point(field_list:Oreka.AllSymbolgroupinfo.symbolgroups)
  return _internal_symbolgroups();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::AllSymbolgroupinfo_Symbolgroups>&
AllSymbolgroupinfo::_internal_symbolgroups() const {
  return _impl_.symbolgroups_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::AllSymbolgroupinfo_Symbolgroups>*
AllSymbolgroupinfo::_internal_mutable_symbolgroups() {
  return &_impl_.symbolgroups_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Oreka


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_AllSymbolgroupinfo_2eproto_2epb_2eh
