//Client position
syntax = "proto3";
package Oreka;
message Clientposition {

    message Insert {
        string login = 1;
        string symbol = 2;
		optional string  name=3;
		optional string symbolExtra=4;
		optional float previousvolume=5;
		optional float difference=6;
		float volume=7;
		optional float average=8;
		optional float lastrate=9;
		optional float clientbalance=10;
		optional float clientnetamount=11;
		optional float maxallotedqty=12;
		optional string company=13;
		optional string subbroker=14;
		optional string broker=15;
		optional float extravolume=16;
		optional float freemargin=17;
		optional float totaltradedlot=18;
		optional float totaltradedto=19;
		optional float companyvolume=20;
		optional float brokervolume=21;
		optional float subbrokervolume=22;
		optional float clientbrokerage=23;
		optional float brokerbrokerage=24;
		optional float subbrokerbrokerage=25;
		optional float companybrokerage=26;
		optional float clientexposure=27;
		optional float Companyexposure=28;
		optional float brokerexposure=29;
		optional float subbrokerexposure=30;
		optional float clientfloatingpl=31;
		optional float companyfloatingpl=32;
		optional float brokerfloatingpl=33;
		optional float subbrokerfloatingpl=34;
		optional float clientbalancepl=35;
		optional float companybalancepl=36;
		optional float brokerbalancepl=37;
		optional float subbrokerbalancepl=38;
		optional float clientplnet=39;
		optional float companyplnet=40;
		optional float brokerplnet=41;
		optional float subbrokerplnet=42;
		optional float clientpatti=43;
		optional float companypatti=44;
		optional float brokerpatti=45;
		optional float subbrokerpatti=46;
		optional float companybrokeragerate=47;
		optional float brokerbrokeragerate=48;
		optional float subbrokerbrokeragerate=49;
		optional float clientbrokeragerate=510;
		optional float clientgrossamount=51;
		optional float brokergrossamount=52;
		optional float subbrokergrossamount=53;
		optional float companygrossamount=54;
		optional string exchange=55;
		optional string international=56;
		optional string sector=57;
		optional string industry=58;
		optional string buysell=59;
		optional string debitcredit=60;
		optional string page=61;
		optional string categary=62;
		optional float rm=63;
		optional float qtyaftermulti=64;
		optional float rmp=65;
		optional float qtymulti=66;
		optional float lpratio=67;
		optional float lpvolume=68;
		optional string commoditygroup=69;
		optional string currencybase=70;			
		optional uint32 TotalNo_Of_StopBuy=71;
		optional uint32 TotalNo_Of_Cancelled_StopBuy=72;
		optional uint32 TotalNo_Of_Passed_StopBuy=73;
		optional uint32 TotalNo_Of_Pending_StopBuy=74;
		optional uint32 TotalNo_Of_StopSell=75;
		optional uint32 TotalNo_Of_Cancelled_StopSell=76;
		optional uint32 TotalNo_Of_Passed_StopSell=77;
		optional uint32 TotalNo_Of_Pending_StopSell=78;
		optional uint32 TotalNo_Of_BuyLimit=79;
		optional uint32 TotalNo_Of_Cancelled_BuyLimit=80;
		optional uint32 TotalNo_Of_Passed_BuyLimit=81;
		optional uint32 TotalNo_Of_Pending_BuyLimit=82;
		optional uint32 TotalNo_Of_SellLimit=83;
		optional uint32 TotalNo_Of_Cancelled_SellLimit=84;
		optional uint32 TotalNo_Of_Passed_SellLimit=85;
		optional uint32 TotalNo_Of_Pending_SellLimit=86;
		optional uint32 TotalNo_Of_MarketDeal=87;
		optional uint32 TotalNo_Of_LimitDeal=88;
		optional uint32 TotalNo_Of_StopLimitDeal=89;

    }

message Update {
        string login = 1;
        string symbol = 2;
		optional string  name=3;
		optional string symbolExtra=4;
		optional float previousvolume=5;
		optional float difference=6;
		float volume=7;
		optional float average=8;
		optional float lastrate=9;
		optional float clientbalance=10;
		optional float clientnetamount=11;
		optional float maxallotedqty=12;
		optional string company=13;
		optional string subbroker=14;
		optional string broker=15;
		optional float extravolume=16;
		optional float freemargin=17;
		optional float totaltradedlot=18;
		optional float totaltradedto=19;
		optional float companyvolume=20;
		optional float brokervolume=21;
		optional float subbrokervolume=22;
		optional float clientbrokerage=23;
		optional float brokerbrokerage=24;
		optional float subbrokerbrokerage=25;
		optional float companybrokerage=26;
		optional float clientexposure=27;
		optional float Companyexposure=28;
		optional float brokerexposure=29;
		optional float subbrokerexposure=30;
		optional float clientfloatingpl=31;
		optional float companyfloatingpl=32;
		optional float brokerfloatingpl=33;
		optional float subbrokerfloatingpl=34;
		optional float clientbalancepl=35;
		optional float companybalancepl=36;
		optional float brokerbalancepl=37;
		optional float subbrokerbalancepl=38;
		optional float clientplnet=39;
		optional float companyplnet=40;
		optional float brokerplnet=41;
		optional float subbrokerplnet=42;
		optional float clientpatti=43;
		optional float companypatti=44;
		optional float brokerpatti=45;
		optional float subbrokerpatti=46;
		optional float companybrokeragerate=47;
		optional float brokerbrokeragerate=48;
		optional float subbrokerbrokeragerate=49;
		optional float clientbrokeragerate=510;
		optional float clientgrossamount=51;
		optional float brokergrossamount=52;
		optional float subbrokergrossamount=53;
		optional float companygrossamount=54;
		optional string exchange=55;
		optional string international=56;
		optional string sector=57;
		optional string industry=58;
		optional string buysell=59;
		optional string debitcredit=60;
		optional string page=61;
		optional string categary=62;
		optional float rm=63;
		optional float qtyaftermulti=64;
		optional float rmp=65;
		optional float qtymulti=66;
		optional float lpratio=67;
		optional float lpvolume=68;
		optional string commoditygroup=69;
		optional string currencybase=70;
		optional uint32 TotalNo_Of_StopBuy=71;
		optional uint32 TotalNo_Of_Cancelled_StopBuy=72;
		optional uint32 TotalNo_Of_Passed_StopBuy=73;
		optional uint32 TotalNo_Of_Pending_StopBuy=74;
		optional uint32 TotalNo_Of_StopSell=75;
		optional uint32 TotalNo_Of_Cancelled_StopSell=76;
		optional uint32 TotalNo_Of_Passed_StopSell=77;
		optional uint32 TotalNo_Of_Pending_StopSell=78;
		optional uint32 TotalNo_Of_BuyLimit=79;
		optional uint32 TotalNo_Of_Cancelled_BuyLimit=80;
		optional uint32 TotalNo_Of_Passed_BuyLimit=81;
		optional uint32 TotalNo_Of_Pending_BuyLimit=82;
		optional uint32 TotalNo_Of_SellLimit=83;
		optional uint32 TotalNo_Of_Cancelled_SellLimit=84;
		optional uint32 TotalNo_Of_Passed_SellLimit=85;
		optional uint32 TotalNo_Of_Pending_SellLimit=86;
		optional uint32 TotalNo_Of_MarketDeal=87;
		optional uint32 TotalNo_Of_LimitDeal=88;
		optional uint32 TotalNo_Of_StopLimitDeal=89;
    }

    string type = 1;
    repeated Insert insert = 2;
	repeated string updatekey = 3;
    repeated Update update = 4;
}