syntax = "proto3";
package Oreka;
import "FetchSymbolgroupinfo.proto";
import "FetchSubbrokerData.proto";
import "loginrequest.proto";
import "loginresponse.proto";
import "FetchLoginUserWiseDataRequest.proto";
import "ActiveColumnChanged.proto";
import "FetchClientPositions.proto";
import "FetchDealingDataInterval.proto";
import "FetchPageDetails.proto";
import "HbS.proto";
import "LoginByToken.proto";
import "FetchBrokerData.proto";
import "FetchClientData.proto";
import "Unsubscribe.proto";
import "ClosingUpdateUpload.proto";
import "UserData.proto";
import "Subbrokerdata.proto";
import "Brokerdata.proto";
import "Clientdata.proto";
import "DealingDataInterval.proto";
import "Dashboard.proto";
import "GatewayPositiondevideratioUpdate.proto";
import "Symbolgroupinfo.proto";
import "AllSymbolgroupinfo.proto";
import "Clientcredit.proto";
import "UpdateClientcredit.proto";
import "ServerMessage.proto";
import "SetSelectedTheme.proto";
import "SelectedTheme.proto";
import "DeletePage.proto";
import "PageList.proto";
import "UpdatePageSequence.proto";
import "ColorThemes.proto";
import "FetchColorTheme.proto";
import "ColorTheme.proto";
import "SaveColorTemplate.proto";
import "DeleteTemplate.ptoto";
import "DeleteColorTheme.proto";
import "FetchColorTemplates.proto";
import "PageDetails.proto";
import "ClientMasterData.proto";
import "SymbolMasterData.proto";
import "ClientPositionUpdate.proto";
import "UserDetails.proto";
import "SubscribeTicker.proto";
import  "ColorTemplates.proto";
import  "MetaData.proto";
import "ClientAndSymbol.proto";
import "TdhResponseMessage.proto";
import "TdhExecution.proto";
import "FetchHighLowMismatchData.proto";
import "HighLowMismatchData.proto";
import "SaveColorTheme.proto";
import "ClientpositionInsertandUpdate.proto";
import "UpdateDataByTablename.proto";
import "AllGroupData.proto";
import "BalanceTransferRequest.proto";
import "TotalClientForBalanceTransfer.proto";
import "TickData.proto";
import "DealingData.proto";
import "BalanceTransferStatus.proto";
import "BalanceTransferResponse.proto";
import "TypeAndFileName.proto";
import "PositionMatchReport.proto";
import "DeleteDataRequest.proto";
import "TotalNoOfData.proto";
import "DeleteDataStatus.proto";
import "DataDeleteResponse.proto";
import "DealTransferRequest.proto";
import "TotalDealForTransfer.proto";
import "PositiontransferStatus.proto";
import "PositionTransferResponse.proto";
import "TradeDateChange.proto";
import "IgnoreClosingandsave.proto";
import "UpdateRejectlimitSetting.proto";
import "SavePage.proto";
import "SavePageRes.proto";
import "OrderData.proto";
import "OrderActivateRequest.proto";
import "OrderActivateResponse.proto";
import "SymbolmappingData.proto";
import "UpdateSymbolmargin.proto";
import "LoginByKey.proto";
import "SetAuthKey.proto";	
import "AlertMessage.proto";
message ClientMessage 
{
    string 										type = 1;
    optional LoginRequest   					loginrequest = 2;
    optional LoginResponse  					loginresponse = 3;
	optional FetchLoginUserWiseDataRequest 		typeandloginrequest=4;
	optional ActiveColumnChanged				activecolumnchagerequest=5;
	optional FetchClientPositions           	fetchclientposition=6;
	optional FetchDealingDataInterval       	fetchDealingdatainterval=7;
	optional FetchPageDetails               	fetchpagedetails=8;
	optional HbS								hbs=9;
	optional LoginByToken						loginbytoken=10;    
	optional FetchSubbrokerData					fetchsubbrokerdata=11;
	optional FetchBrokerData					fetchbrokerdata=12;
	optional FetchClientData					fetchclientdata=13;
	optional Unsubscribe						unsubscribe=14;
	optional ClosingUpdateUpload				closingupdateupload=15;
	optional UserData							userdata=16;
	optional Subbrokerdata               		subbrokerdata=17;
	optional Brokerdata  						brokerdata=18;
	optional Clientdata							clientdata=19;	
	optional DealingDataInterval            	dealingdatainterval=20; 
	optional Dashboard							dashboard=21;
	optional GatewayPositiondevideratioUpdate	gatewaypositiondevideratioupdate=22;
	optional FetchSymbolgroupinfo				fetchsymbolgroupinfo=23;
	optional Symbolgroupinfo					symbolgroupinfo=24;
	optional AllSymbolgroupinfo					allsymbolgroupinfo=25;
	optional Clientcredit						clientcredit=26;
	optional UpdateClientcredit					updateclientcredit=27;
	optional ServerMessage						servermessage=28;
	optional SetSelectedTheme					setselectedtheme=29;
	optional SelectedTheme						selectedtheme=30;
	optional DeletePage							deletepage=31;
	optional PageList							pagelist=32;
	optional UpdatePageSequence					updatepagesequence=33;
	optional ColorThemes						colorthemes=34;
	optional FetchColorTheme					fetchColortheme=35;
	optional ColorTheme							colorTheme=36;
	optional SaveColorTemplate					saveColorTemplate=37;
	optional DeleteTemplate						deletetemplate=38;
	optional DeleteColorTheme					deletecolortheme=39;
	optional FetchColorTemplates				fetchcolortemplates=40;
	optional PageDetails						pagedetails=41;
	optional ClientMasterData					clientmasterdata=42;
	optional SymbolMasterData					symbolmastersata=43;
	optional ClientPositionUpdate				clientpositionupdate=44;
	optional UserDetails						userdetails=45;
	optional SubscribeTicker					subscribeticker=46;
	optional ColorTemplates						colortemplates=47;
	optional MetaData							metadata=48;
	optional ClientAndSymbol					clientandsymbol=49;
	optional TdhResponseMessage					tdhresponsemessage=50;
	optional TdhExecution						tdhexecution=51;
	optional FetchHighLowMismatchData			fetchhighlowmismatchdata=52;
	optional HighLowMismatchData				highlowmismatchdata=53;
	optional SaveColorTheme						savecolortheme=54;
	optional ClientpositionInsertandUpdate		clientposition=55;
	optional UpdateDataByTablename				updatedatabytablename=56;
	optional AllGroupData						allgroupdata=57;
	optional BalanceTransferRequest				balancetransferrequest=58;
	optional TotalClientForBalanceTransfer		totalclientforbalancetransfer=59;
	optional DealingData						dealingdata=60;
	optional TickData							tickdata=61;	
	optional BalanceTransferStatus				balancetransferstatus=62;	
	optional BalanceTransferResponse			balancetransferresponse=63;
	optional TypeAndFileName					typeandfilename=64;
	optional PositionMatchReport				positionmatchreport=65;
	optional DeleteDataRequest					deletedatarequest=66;
	optional TotalNoOfData						totalnoofdata=67;
	optional DeleteDataStatus					deletedatastatus=68;
	optional DataDeleteResponse					datadeleteresponse=69;
	optional DealTransferRequest				dealtransferrequest=70;
	optional TotalDealForTransfer				totaldealfortransfer=71;
	optional PositiontransferStatus				positiontransferstatus=72;
	optional PositionTransferResponse			positiontransferresponse=73;
	optional TradeDateChange					tradedatechange=74;
	optional IgnoreClosingandsave				ignoreclosingandsave=75;
	optional UpdateRejectlimitSetting			updaterejectlimitsetting=76;
	optional SavePage							savepage=77;
	optional SavePageRes						savepageres=78;
	optional OrderData							orderdata=79;
	optional OrderActivateRequest				orderactivaterequest=80;
	optional OrderActivateResponse				orderactivateresponse=81;
	optional SymbolmappingData					symbolmappingdata=82;
	optional UpdateSymbolmargin					updatesymbolmargin=83;
	optional LoginByKey							loginbykey=84;
	optional SetAuthKey							setauthkey=85;
	optional AlertMessage						alertmessage=86;
}