// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dashboard.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Dashboard_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Dashboard_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Dashboard_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Dashboard_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_Dashboard_2eproto;
namespace Oreka {
class Dashboard;
struct DashboardDefaultTypeInternal;
extern DashboardDefaultTypeInternal _Dashboard_default_instance_;
class Dashboard_Data;
struct Dashboard_DataDefaultTypeInternal;
extern Dashboard_DataDefaultTypeInternal _Dashboard_Data_default_instance_;
class Dashboard_Gridcolumndata;
struct Dashboard_GridcolumndataDefaultTypeInternal;
extern Dashboard_GridcolumndataDefaultTypeInternal _Dashboard_Gridcolumndata_default_instance_;
class Dashboard_Gridlayoutlocation;
struct Dashboard_GridlayoutlocationDefaultTypeInternal;
extern Dashboard_GridlayoutlocationDefaultTypeInternal _Dashboard_Gridlayoutlocation_default_instance_;
class Dashboard_Gridproperties;
struct Dashboard_GridpropertiesDefaultTypeInternal;
extern Dashboard_GridpropertiesDefaultTypeInternal _Dashboard_Gridproperties_default_instance_;
}  // namespace Oreka
PROTOBUF_NAMESPACE_OPEN
template <>
::Oreka::Dashboard* Arena::CreateMaybeMessage<::Oreka::Dashboard>(Arena*);
template <>
::Oreka::Dashboard_Data* Arena::CreateMaybeMessage<::Oreka::Dashboard_Data>(Arena*);
template <>
::Oreka::Dashboard_Gridcolumndata* Arena::CreateMaybeMessage<::Oreka::Dashboard_Gridcolumndata>(Arena*);
template <>
::Oreka::Dashboard_Gridlayoutlocation* Arena::CreateMaybeMessage<::Oreka::Dashboard_Gridlayoutlocation>(Arena*);
template <>
::Oreka::Dashboard_Gridproperties* Arena::CreateMaybeMessage<::Oreka::Dashboard_Gridproperties>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace Oreka {

// ===================================================================


// -------------------------------------------------------------------

class Dashboard_Gridlayoutlocation final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Oreka.Dashboard.Gridlayoutlocation) */ {
 public:
  inline Dashboard_Gridlayoutlocation() : Dashboard_Gridlayoutlocation(nullptr) {}
  ~Dashboard_Gridlayoutlocation() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Dashboard_Gridlayoutlocation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Dashboard_Gridlayoutlocation(const Dashboard_Gridlayoutlocation& from);
  Dashboard_Gridlayoutlocation(Dashboard_Gridlayoutlocation&& from) noexcept
    : Dashboard_Gridlayoutlocation() {
    *this = ::std::move(from);
  }

  inline Dashboard_Gridlayoutlocation& operator=(const Dashboard_Gridlayoutlocation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Dashboard_Gridlayoutlocation& operator=(Dashboard_Gridlayoutlocation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Dashboard_Gridlayoutlocation& default_instance() {
    return *internal_default_instance();
  }
  static inline const Dashboard_Gridlayoutlocation* internal_default_instance() {
    return reinterpret_cast<const Dashboard_Gridlayoutlocation*>(
               &_Dashboard_Gridlayoutlocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Dashboard_Gridlayoutlocation& a, Dashboard_Gridlayoutlocation& b) {
    a.Swap(&b);
  }
  inline void Swap(Dashboard_Gridlayoutlocation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Dashboard_Gridlayoutlocation* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Dashboard_Gridlayoutlocation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Dashboard_Gridlayoutlocation>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Dashboard_Gridlayoutlocation& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Dashboard_Gridlayoutlocation& from) {
    Dashboard_Gridlayoutlocation::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Dashboard_Gridlayoutlocation* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Oreka.Dashboard.Gridlayoutlocation";
  }
  protected:
  explicit Dashboard_Gridlayoutlocation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kWFieldNumber = 4,
    kHFieldNumber = 5,
  };
  // string i = 1;
  void clear_i() ;
  const std::string& i() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_i(Arg_&& arg, Args_... args);
  std::string* mutable_i();
  PROTOBUF_NODISCARD std::string* release_i();
  void set_allocated_i(std::string* ptr);

  private:
  const std::string& _internal_i() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_i(
      const std::string& value);
  std::string* _internal_mutable_i();

  public:
  // uint32 x = 2;
  void clear_x() ;
  ::uint32_t x() const;
  void set_x(::uint32_t value);

  private:
  ::uint32_t _internal_x() const;
  void _internal_set_x(::uint32_t value);

  public:
  // uint32 y = 3;
  void clear_y() ;
  ::uint32_t y() const;
  void set_y(::uint32_t value);

  private:
  ::uint32_t _internal_y() const;
  void _internal_set_y(::uint32_t value);

  public:
  // uint32 w = 4;
  void clear_w() ;
  ::uint32_t w() const;
  void set_w(::uint32_t value);

  private:
  ::uint32_t _internal_w() const;
  void _internal_set_w(::uint32_t value);

  public:
  // uint32 h = 5;
  void clear_h() ;
  ::uint32_t h() const;
  void set_h(::uint32_t value);

  private:
  ::uint32_t _internal_h() const;
  void _internal_set_h(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Oreka.Dashboard.Gridlayoutlocation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr i_;
    ::uint32_t x_;
    ::uint32_t y_;
    ::uint32_t w_;
    ::uint32_t h_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Dashboard_2eproto;
};// -------------------------------------------------------------------

class Dashboard_Gridproperties final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Oreka.Dashboard.Gridproperties) */ {
 public:
  inline Dashboard_Gridproperties() : Dashboard_Gridproperties(nullptr) {}
  ~Dashboard_Gridproperties() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Dashboard_Gridproperties(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Dashboard_Gridproperties(const Dashboard_Gridproperties& from);
  Dashboard_Gridproperties(Dashboard_Gridproperties&& from) noexcept
    : Dashboard_Gridproperties() {
    *this = ::std::move(from);
  }

  inline Dashboard_Gridproperties& operator=(const Dashboard_Gridproperties& from) {
    CopyFrom(from);
    return *this;
  }
  inline Dashboard_Gridproperties& operator=(Dashboard_Gridproperties&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Dashboard_Gridproperties& default_instance() {
    return *internal_default_instance();
  }
  static inline const Dashboard_Gridproperties* internal_default_instance() {
    return reinterpret_cast<const Dashboard_Gridproperties*>(
               &_Dashboard_Gridproperties_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Dashboard_Gridproperties& a, Dashboard_Gridproperties& b) {
    a.Swap(&b);
  }
  inline void Swap(Dashboard_Gridproperties* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Dashboard_Gridproperties* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Dashboard_Gridproperties* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Dashboard_Gridproperties>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Dashboard_Gridproperties& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Dashboard_Gridproperties& from) {
    Dashboard_Gridproperties::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Dashboard_Gridproperties* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Oreka.Dashboard.Gridproperties";
  }
  protected:
  explicit Dashboard_Gridproperties(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGridLayoutLocationFieldNumber = 2,
    kHideFieldNumber = 1,
  };
  // .Oreka.Dashboard.Gridlayoutlocation gridLayoutLocation = 2;
  bool has_gridlayoutlocation() const;
  void clear_gridlayoutlocation() ;
  const ::Oreka::Dashboard_Gridlayoutlocation& gridlayoutlocation() const;
  PROTOBUF_NODISCARD ::Oreka::Dashboard_Gridlayoutlocation* release_gridlayoutlocation();
  ::Oreka::Dashboard_Gridlayoutlocation* mutable_gridlayoutlocation();
  void set_allocated_gridlayoutlocation(::Oreka::Dashboard_Gridlayoutlocation* gridlayoutlocation);
  private:
  const ::Oreka::Dashboard_Gridlayoutlocation& _internal_gridlayoutlocation() const;
  ::Oreka::Dashboard_Gridlayoutlocation* _internal_mutable_gridlayoutlocation();
  public:
  void unsafe_arena_set_allocated_gridlayoutlocation(
      ::Oreka::Dashboard_Gridlayoutlocation* gridlayoutlocation);
  ::Oreka::Dashboard_Gridlayoutlocation* unsafe_arena_release_gridlayoutlocation();
  // bool hide = 1;
  void clear_hide() ;
  bool hide() const;
  void set_hide(bool value);

  private:
  bool _internal_hide() const;
  void _internal_set_hide(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Oreka.Dashboard.Gridproperties)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::Oreka::Dashboard_Gridlayoutlocation* gridlayoutlocation_;
    bool hide_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Dashboard_2eproto;
};// -------------------------------------------------------------------

class Dashboard_Data final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Oreka.Dashboard.Data) */ {
 public:
  inline Dashboard_Data() : Dashboard_Data(nullptr) {}
  ~Dashboard_Data() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Dashboard_Data(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Dashboard_Data(const Dashboard_Data& from);
  Dashboard_Data(Dashboard_Data&& from) noexcept
    : Dashboard_Data() {
    *this = ::std::move(from);
  }

  inline Dashboard_Data& operator=(const Dashboard_Data& from) {
    CopyFrom(from);
    return *this;
  }
  inline Dashboard_Data& operator=(Dashboard_Data&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Dashboard_Data& default_instance() {
    return *internal_default_instance();
  }
  static inline const Dashboard_Data* internal_default_instance() {
    return reinterpret_cast<const Dashboard_Data*>(
               &_Dashboard_Data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Dashboard_Data& a, Dashboard_Data& b) {
    a.Swap(&b);
  }
  inline void Swap(Dashboard_Data* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Dashboard_Data* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Dashboard_Data* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Dashboard_Data>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Dashboard_Data& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Dashboard_Data& from) {
    Dashboard_Data::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Dashboard_Data* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Oreka.Dashboard.Data";
  }
  protected:
  explicit Dashboard_Data(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFieldFieldNumber = 1,
    kPinnedFieldNumber = 4,
    kWidthFieldNumber = 2,
    kOrderFieldNumber = 3,
    kRowGroupFieldNumber = 5,
    kHideFieldNumber = 6,
    kCollapsedFieldNumber = 7,
  };
  // string field = 1;
  void clear_field() ;
  const std::string& field() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_field(Arg_&& arg, Args_... args);
  std::string* mutable_field();
  PROTOBUF_NODISCARD std::string* release_field();
  void set_allocated_field(std::string* ptr);

  private:
  const std::string& _internal_field() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_field(
      const std::string& value);
  std::string* _internal_mutable_field();

  public:
  // string pinned = 4;
  void clear_pinned() ;
  const std::string& pinned() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pinned(Arg_&& arg, Args_... args);
  std::string* mutable_pinned();
  PROTOBUF_NODISCARD std::string* release_pinned();
  void set_allocated_pinned(std::string* ptr);

  private:
  const std::string& _internal_pinned() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pinned(
      const std::string& value);
  std::string* _internal_mutable_pinned();

  public:
  // uint32 width = 2;
  void clear_width() ;
  ::uint32_t width() const;
  void set_width(::uint32_t value);

  private:
  ::uint32_t _internal_width() const;
  void _internal_set_width(::uint32_t value);

  public:
  // uint32 order = 3;
  void clear_order() ;
  ::uint32_t order() const;
  void set_order(::uint32_t value);

  private:
  ::uint32_t _internal_order() const;
  void _internal_set_order(::uint32_t value);

  public:
  // bool rowGroup = 5;
  void clear_rowgroup() ;
  bool rowgroup() const;
  void set_rowgroup(bool value);

  private:
  bool _internal_rowgroup() const;
  void _internal_set_rowgroup(bool value);

  public:
  // bool hide = 6;
  void clear_hide() ;
  bool hide() const;
  void set_hide(bool value);

  private:
  bool _internal_hide() const;
  void _internal_set_hide(bool value);

  public:
  // bool collapsed = 7;
  void clear_collapsed() ;
  bool collapsed() const;
  void set_collapsed(bool value);

  private:
  bool _internal_collapsed() const;
  void _internal_set_collapsed(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Oreka.Dashboard.Data)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr field_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pinned_;
    ::uint32_t width_;
    ::uint32_t order_;
    bool rowgroup_;
    bool hide_;
    bool collapsed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Dashboard_2eproto;
};// -------------------------------------------------------------------

class Dashboard_Gridcolumndata final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Oreka.Dashboard.Gridcolumndata) */ {
 public:
  inline Dashboard_Gridcolumndata() : Dashboard_Gridcolumndata(nullptr) {}
  ~Dashboard_Gridcolumndata() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Dashboard_Gridcolumndata(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Dashboard_Gridcolumndata(const Dashboard_Gridcolumndata& from);
  Dashboard_Gridcolumndata(Dashboard_Gridcolumndata&& from) noexcept
    : Dashboard_Gridcolumndata() {
    *this = ::std::move(from);
  }

  inline Dashboard_Gridcolumndata& operator=(const Dashboard_Gridcolumndata& from) {
    CopyFrom(from);
    return *this;
  }
  inline Dashboard_Gridcolumndata& operator=(Dashboard_Gridcolumndata&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Dashboard_Gridcolumndata& default_instance() {
    return *internal_default_instance();
  }
  static inline const Dashboard_Gridcolumndata* internal_default_instance() {
    return reinterpret_cast<const Dashboard_Gridcolumndata*>(
               &_Dashboard_Gridcolumndata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Dashboard_Gridcolumndata& a, Dashboard_Gridcolumndata& b) {
    a.Swap(&b);
  }
  inline void Swap(Dashboard_Gridcolumndata* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Dashboard_Gridcolumndata* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Dashboard_Gridcolumndata* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Dashboard_Gridcolumndata>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Dashboard_Gridcolumndata& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Dashboard_Gridcolumndata& from) {
    Dashboard_Gridcolumndata::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Dashboard_Gridcolumndata* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Oreka.Dashboard.Gridcolumndata";
  }
  protected:
  explicit Dashboard_Gridcolumndata(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 4,
    kFieldFieldNumber = 1,
    kTypeFieldNumber = 2,
    kGridPropertiesFieldNumber = 3,
  };
  // repeated .Oreka.Dashboard.Data data = 4;
  int data_size() const;
  private:
  int _internal_data_size() const;

  public:
  void clear_data() ;
  ::Oreka::Dashboard_Data* mutable_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::Dashboard_Data >*
      mutable_data();
  private:
  const ::Oreka::Dashboard_Data& _internal_data(int index) const;
  ::Oreka::Dashboard_Data* _internal_add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::Dashboard_Data>& _internal_data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::Dashboard_Data>* _internal_mutable_data();
  public:
  const ::Oreka::Dashboard_Data& data(int index) const;
  ::Oreka::Dashboard_Data* add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::Dashboard_Data >&
      data() const;
  // string field = 1;
  void clear_field() ;
  const std::string& field() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_field(Arg_&& arg, Args_... args);
  std::string* mutable_field();
  PROTOBUF_NODISCARD std::string* release_field();
  void set_allocated_field(std::string* ptr);

  private:
  const std::string& _internal_field() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_field(
      const std::string& value);
  std::string* _internal_mutable_field();

  public:
  // string type = 2;
  void clear_type() ;
  const std::string& type() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* ptr);

  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(
      const std::string& value);
  std::string* _internal_mutable_type();

  public:
  // .Oreka.Dashboard.Gridproperties gridProperties = 3;
  bool has_gridproperties() const;
  void clear_gridproperties() ;
  const ::Oreka::Dashboard_Gridproperties& gridproperties() const;
  PROTOBUF_NODISCARD ::Oreka::Dashboard_Gridproperties* release_gridproperties();
  ::Oreka::Dashboard_Gridproperties* mutable_gridproperties();
  void set_allocated_gridproperties(::Oreka::Dashboard_Gridproperties* gridproperties);
  private:
  const ::Oreka::Dashboard_Gridproperties& _internal_gridproperties() const;
  ::Oreka::Dashboard_Gridproperties* _internal_mutable_gridproperties();
  public:
  void unsafe_arena_set_allocated_gridproperties(
      ::Oreka::Dashboard_Gridproperties* gridproperties);
  ::Oreka::Dashboard_Gridproperties* unsafe_arena_release_gridproperties();
  // @@protoc_insertion_point(class_scope:Oreka.Dashboard.Gridcolumndata)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::Dashboard_Data > data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr field_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    ::Oreka::Dashboard_Gridproperties* gridproperties_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Dashboard_2eproto;
};// -------------------------------------------------------------------

class Dashboard final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Oreka.Dashboard) */ {
 public:
  inline Dashboard() : Dashboard(nullptr) {}
  ~Dashboard() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Dashboard(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Dashboard(const Dashboard& from);
  Dashboard(Dashboard&& from) noexcept
    : Dashboard() {
    *this = ::std::move(from);
  }

  inline Dashboard& operator=(const Dashboard& from) {
    CopyFrom(from);
    return *this;
  }
  inline Dashboard& operator=(Dashboard&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Dashboard& default_instance() {
    return *internal_default_instance();
  }
  static inline const Dashboard* internal_default_instance() {
    return reinterpret_cast<const Dashboard*>(
               &_Dashboard_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Dashboard& a, Dashboard& b) {
    a.Swap(&b);
  }
  inline void Swap(Dashboard* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Dashboard* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Dashboard* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Dashboard>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Dashboard& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Dashboard& from) {
    Dashboard::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Dashboard* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Oreka.Dashboard";
  }
  protected:
  explicit Dashboard(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Dashboard_Gridlayoutlocation Gridlayoutlocation;
  typedef Dashboard_Gridproperties Gridproperties;
  typedef Dashboard_Data Data;
  typedef Dashboard_Gridcolumndata Gridcolumndata;

  // accessors -------------------------------------------------------

  enum : int {
    kGridcolumndataFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // repeated .Oreka.Dashboard.Gridcolumndata gridcolumndata = 2;
  int gridcolumndata_size() const;
  private:
  int _internal_gridcolumndata_size() const;

  public:
  void clear_gridcolumndata() ;
  ::Oreka::Dashboard_Gridcolumndata* mutable_gridcolumndata(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::Dashboard_Gridcolumndata >*
      mutable_gridcolumndata();
  private:
  const ::Oreka::Dashboard_Gridcolumndata& _internal_gridcolumndata(int index) const;
  ::Oreka::Dashboard_Gridcolumndata* _internal_add_gridcolumndata();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::Dashboard_Gridcolumndata>& _internal_gridcolumndata() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::Dashboard_Gridcolumndata>* _internal_mutable_gridcolumndata();
  public:
  const ::Oreka::Dashboard_Gridcolumndata& gridcolumndata(int index) const;
  ::Oreka::Dashboard_Gridcolumndata* add_gridcolumndata();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::Dashboard_Gridcolumndata >&
      gridcolumndata() const;
  // string type = 1;
  void clear_type() ;
  const std::string& type() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* ptr);

  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(
      const std::string& value);
  std::string* _internal_mutable_type();

  public:
  // @@protoc_insertion_point(class_scope:Oreka.Dashboard)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::Dashboard_Gridcolumndata > gridcolumndata_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Dashboard_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Dashboard_Gridlayoutlocation

// string i = 1;
inline void Dashboard_Gridlayoutlocation::clear_i() {
  _impl_.i_.ClearToEmpty();
}
inline const std::string& Dashboard_Gridlayoutlocation::i() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Gridlayoutlocation.i)
  return _internal_i();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Dashboard_Gridlayoutlocation::set_i(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.i_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Gridlayoutlocation.i)
}
inline std::string* Dashboard_Gridlayoutlocation::mutable_i() {
  std::string* _s = _internal_mutable_i();
  // @@protoc_insertion_point(field_mutable:Oreka.Dashboard.Gridlayoutlocation.i)
  return _s;
}
inline const std::string& Dashboard_Gridlayoutlocation::_internal_i() const {
  return _impl_.i_.Get();
}
inline void Dashboard_Gridlayoutlocation::_internal_set_i(const std::string& value) {
  ;


  _impl_.i_.Set(value, GetArenaForAllocation());
}
inline std::string* Dashboard_Gridlayoutlocation::_internal_mutable_i() {
  ;
  return _impl_.i_.Mutable( GetArenaForAllocation());
}
inline std::string* Dashboard_Gridlayoutlocation::release_i() {
  // @@protoc_insertion_point(field_release:Oreka.Dashboard.Gridlayoutlocation.i)
  return _impl_.i_.Release();
}
inline void Dashboard_Gridlayoutlocation::set_allocated_i(std::string* value) {
  _impl_.i_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.i_.IsDefault()) {
          _impl_.i_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.Dashboard.Gridlayoutlocation.i)
}

// uint32 x = 2;
inline void Dashboard_Gridlayoutlocation::clear_x() {
  _impl_.x_ = 0u;
}
inline ::uint32_t Dashboard_Gridlayoutlocation::x() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Gridlayoutlocation.x)
  return _internal_x();
}
inline void Dashboard_Gridlayoutlocation::set_x(::uint32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Gridlayoutlocation.x)
}
inline ::uint32_t Dashboard_Gridlayoutlocation::_internal_x() const {
  return _impl_.x_;
}
inline void Dashboard_Gridlayoutlocation::_internal_set_x(::uint32_t value) {
  ;
  _impl_.x_ = value;
}

// uint32 y = 3;
inline void Dashboard_Gridlayoutlocation::clear_y() {
  _impl_.y_ = 0u;
}
inline ::uint32_t Dashboard_Gridlayoutlocation::y() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Gridlayoutlocation.y)
  return _internal_y();
}
inline void Dashboard_Gridlayoutlocation::set_y(::uint32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Gridlayoutlocation.y)
}
inline ::uint32_t Dashboard_Gridlayoutlocation::_internal_y() const {
  return _impl_.y_;
}
inline void Dashboard_Gridlayoutlocation::_internal_set_y(::uint32_t value) {
  ;
  _impl_.y_ = value;
}

// uint32 w = 4;
inline void Dashboard_Gridlayoutlocation::clear_w() {
  _impl_.w_ = 0u;
}
inline ::uint32_t Dashboard_Gridlayoutlocation::w() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Gridlayoutlocation.w)
  return _internal_w();
}
inline void Dashboard_Gridlayoutlocation::set_w(::uint32_t value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Gridlayoutlocation.w)
}
inline ::uint32_t Dashboard_Gridlayoutlocation::_internal_w() const {
  return _impl_.w_;
}
inline void Dashboard_Gridlayoutlocation::_internal_set_w(::uint32_t value) {
  ;
  _impl_.w_ = value;
}

// uint32 h = 5;
inline void Dashboard_Gridlayoutlocation::clear_h() {
  _impl_.h_ = 0u;
}
inline ::uint32_t Dashboard_Gridlayoutlocation::h() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Gridlayoutlocation.h)
  return _internal_h();
}
inline void Dashboard_Gridlayoutlocation::set_h(::uint32_t value) {
  _internal_set_h(value);
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Gridlayoutlocation.h)
}
inline ::uint32_t Dashboard_Gridlayoutlocation::_internal_h() const {
  return _impl_.h_;
}
inline void Dashboard_Gridlayoutlocation::_internal_set_h(::uint32_t value) {
  ;
  _impl_.h_ = value;
}

// -------------------------------------------------------------------

// Dashboard_Gridproperties

// bool hide = 1;
inline void Dashboard_Gridproperties::clear_hide() {
  _impl_.hide_ = false;
}
inline bool Dashboard_Gridproperties::hide() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Gridproperties.hide)
  return _internal_hide();
}
inline void Dashboard_Gridproperties::set_hide(bool value) {
  _internal_set_hide(value);
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Gridproperties.hide)
}
inline bool Dashboard_Gridproperties::_internal_hide() const {
  return _impl_.hide_;
}
inline void Dashboard_Gridproperties::_internal_set_hide(bool value) {
  ;
  _impl_.hide_ = value;
}

// .Oreka.Dashboard.Gridlayoutlocation gridLayoutLocation = 2;
inline bool Dashboard_Gridproperties::has_gridlayoutlocation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.gridlayoutlocation_ != nullptr);
  return value;
}
inline void Dashboard_Gridproperties::clear_gridlayoutlocation() {
  if (_impl_.gridlayoutlocation_ != nullptr) _impl_.gridlayoutlocation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Oreka::Dashboard_Gridlayoutlocation& Dashboard_Gridproperties::_internal_gridlayoutlocation() const {
  const ::Oreka::Dashboard_Gridlayoutlocation* p = _impl_.gridlayoutlocation_;
  return p != nullptr ? *p : reinterpret_cast<const ::Oreka::Dashboard_Gridlayoutlocation&>(
      ::Oreka::_Dashboard_Gridlayoutlocation_default_instance_);
}
inline const ::Oreka::Dashboard_Gridlayoutlocation& Dashboard_Gridproperties::gridlayoutlocation() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Gridproperties.gridLayoutLocation)
  return _internal_gridlayoutlocation();
}
inline void Dashboard_Gridproperties::unsafe_arena_set_allocated_gridlayoutlocation(
    ::Oreka::Dashboard_Gridlayoutlocation* gridlayoutlocation) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.gridlayoutlocation_);
  }
  _impl_.gridlayoutlocation_ = gridlayoutlocation;
  if (gridlayoutlocation) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Oreka.Dashboard.Gridproperties.gridLayoutLocation)
}
inline ::Oreka::Dashboard_Gridlayoutlocation* Dashboard_Gridproperties::release_gridlayoutlocation() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Oreka::Dashboard_Gridlayoutlocation* temp = _impl_.gridlayoutlocation_;
  _impl_.gridlayoutlocation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Oreka::Dashboard_Gridlayoutlocation* Dashboard_Gridproperties::unsafe_arena_release_gridlayoutlocation() {
  // @@protoc_insertion_point(field_release:Oreka.Dashboard.Gridproperties.gridLayoutLocation)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Oreka::Dashboard_Gridlayoutlocation* temp = _impl_.gridlayoutlocation_;
  _impl_.gridlayoutlocation_ = nullptr;
  return temp;
}
inline ::Oreka::Dashboard_Gridlayoutlocation* Dashboard_Gridproperties::_internal_mutable_gridlayoutlocation() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.gridlayoutlocation_ == nullptr) {
    auto* p = CreateMaybeMessage<::Oreka::Dashboard_Gridlayoutlocation>(GetArenaForAllocation());
    _impl_.gridlayoutlocation_ = p;
  }
  return _impl_.gridlayoutlocation_;
}
inline ::Oreka::Dashboard_Gridlayoutlocation* Dashboard_Gridproperties::mutable_gridlayoutlocation() {
  ::Oreka::Dashboard_Gridlayoutlocation* _msg = _internal_mutable_gridlayoutlocation();
  // @@protoc_insertion_point(field_mutable:Oreka.Dashboard.Gridproperties.gridLayoutLocation)
  return _msg;
}
inline void Dashboard_Gridproperties::set_allocated_gridlayoutlocation(::Oreka::Dashboard_Gridlayoutlocation* gridlayoutlocation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.gridlayoutlocation_;
  }
  if (gridlayoutlocation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(gridlayoutlocation);
    if (message_arena != submessage_arena) {
      gridlayoutlocation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, gridlayoutlocation, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.gridlayoutlocation_ = gridlayoutlocation;
  // @@protoc_insertion_point(field_set_allocated:Oreka.Dashboard.Gridproperties.gridLayoutLocation)
}

// -------------------------------------------------------------------

// Dashboard_Data

// string field = 1;
inline void Dashboard_Data::clear_field() {
  _impl_.field_.ClearToEmpty();
}
inline const std::string& Dashboard_Data::field() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Data.field)
  return _internal_field();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Dashboard_Data::set_field(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.field_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Data.field)
}
inline std::string* Dashboard_Data::mutable_field() {
  std::string* _s = _internal_mutable_field();
  // @@protoc_insertion_point(field_mutable:Oreka.Dashboard.Data.field)
  return _s;
}
inline const std::string& Dashboard_Data::_internal_field() const {
  return _impl_.field_.Get();
}
inline void Dashboard_Data::_internal_set_field(const std::string& value) {
  ;


  _impl_.field_.Set(value, GetArenaForAllocation());
}
inline std::string* Dashboard_Data::_internal_mutable_field() {
  ;
  return _impl_.field_.Mutable( GetArenaForAllocation());
}
inline std::string* Dashboard_Data::release_field() {
  // @@protoc_insertion_point(field_release:Oreka.Dashboard.Data.field)
  return _impl_.field_.Release();
}
inline void Dashboard_Data::set_allocated_field(std::string* value) {
  _impl_.field_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.field_.IsDefault()) {
          _impl_.field_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.Dashboard.Data.field)
}

// uint32 width = 2;
inline void Dashboard_Data::clear_width() {
  _impl_.width_ = 0u;
}
inline ::uint32_t Dashboard_Data::width() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Data.width)
  return _internal_width();
}
inline void Dashboard_Data::set_width(::uint32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Data.width)
}
inline ::uint32_t Dashboard_Data::_internal_width() const {
  return _impl_.width_;
}
inline void Dashboard_Data::_internal_set_width(::uint32_t value) {
  ;
  _impl_.width_ = value;
}

// uint32 order = 3;
inline void Dashboard_Data::clear_order() {
  _impl_.order_ = 0u;
}
inline ::uint32_t Dashboard_Data::order() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Data.order)
  return _internal_order();
}
inline void Dashboard_Data::set_order(::uint32_t value) {
  _internal_set_order(value);
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Data.order)
}
inline ::uint32_t Dashboard_Data::_internal_order() const {
  return _impl_.order_;
}
inline void Dashboard_Data::_internal_set_order(::uint32_t value) {
  ;
  _impl_.order_ = value;
}

// string pinned = 4;
inline void Dashboard_Data::clear_pinned() {
  _impl_.pinned_.ClearToEmpty();
}
inline const std::string& Dashboard_Data::pinned() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Data.pinned)
  return _internal_pinned();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Dashboard_Data::set_pinned(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.pinned_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Data.pinned)
}
inline std::string* Dashboard_Data::mutable_pinned() {
  std::string* _s = _internal_mutable_pinned();
  // @@protoc_insertion_point(field_mutable:Oreka.Dashboard.Data.pinned)
  return _s;
}
inline const std::string& Dashboard_Data::_internal_pinned() const {
  return _impl_.pinned_.Get();
}
inline void Dashboard_Data::_internal_set_pinned(const std::string& value) {
  ;


  _impl_.pinned_.Set(value, GetArenaForAllocation());
}
inline std::string* Dashboard_Data::_internal_mutable_pinned() {
  ;
  return _impl_.pinned_.Mutable( GetArenaForAllocation());
}
inline std::string* Dashboard_Data::release_pinned() {
  // @@protoc_insertion_point(field_release:Oreka.Dashboard.Data.pinned)
  return _impl_.pinned_.Release();
}
inline void Dashboard_Data::set_allocated_pinned(std::string* value) {
  _impl_.pinned_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pinned_.IsDefault()) {
          _impl_.pinned_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.Dashboard.Data.pinned)
}

// bool rowGroup = 5;
inline void Dashboard_Data::clear_rowgroup() {
  _impl_.rowgroup_ = false;
}
inline bool Dashboard_Data::rowgroup() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Data.rowGroup)
  return _internal_rowgroup();
}
inline void Dashboard_Data::set_rowgroup(bool value) {
  _internal_set_rowgroup(value);
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Data.rowGroup)
}
inline bool Dashboard_Data::_internal_rowgroup() const {
  return _impl_.rowgroup_;
}
inline void Dashboard_Data::_internal_set_rowgroup(bool value) {
  ;
  _impl_.rowgroup_ = value;
}

// bool hide = 6;
inline void Dashboard_Data::clear_hide() {
  _impl_.hide_ = false;
}
inline bool Dashboard_Data::hide() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Data.hide)
  return _internal_hide();
}
inline void Dashboard_Data::set_hide(bool value) {
  _internal_set_hide(value);
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Data.hide)
}
inline bool Dashboard_Data::_internal_hide() const {
  return _impl_.hide_;
}
inline void Dashboard_Data::_internal_set_hide(bool value) {
  ;
  _impl_.hide_ = value;
}

// bool collapsed = 7;
inline void Dashboard_Data::clear_collapsed() {
  _impl_.collapsed_ = false;
}
inline bool Dashboard_Data::collapsed() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Data.collapsed)
  return _internal_collapsed();
}
inline void Dashboard_Data::set_collapsed(bool value) {
  _internal_set_collapsed(value);
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Data.collapsed)
}
inline bool Dashboard_Data::_internal_collapsed() const {
  return _impl_.collapsed_;
}
inline void Dashboard_Data::_internal_set_collapsed(bool value) {
  ;
  _impl_.collapsed_ = value;
}

// -------------------------------------------------------------------

// Dashboard_Gridcolumndata

// string field = 1;
inline void Dashboard_Gridcolumndata::clear_field() {
  _impl_.field_.ClearToEmpty();
}
inline const std::string& Dashboard_Gridcolumndata::field() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Gridcolumndata.field)
  return _internal_field();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Dashboard_Gridcolumndata::set_field(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.field_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Gridcolumndata.field)
}
inline std::string* Dashboard_Gridcolumndata::mutable_field() {
  std::string* _s = _internal_mutable_field();
  // @@protoc_insertion_point(field_mutable:Oreka.Dashboard.Gridcolumndata.field)
  return _s;
}
inline const std::string& Dashboard_Gridcolumndata::_internal_field() const {
  return _impl_.field_.Get();
}
inline void Dashboard_Gridcolumndata::_internal_set_field(const std::string& value) {
  ;


  _impl_.field_.Set(value, GetArenaForAllocation());
}
inline std::string* Dashboard_Gridcolumndata::_internal_mutable_field() {
  ;
  return _impl_.field_.Mutable( GetArenaForAllocation());
}
inline std::string* Dashboard_Gridcolumndata::release_field() {
  // @@protoc_insertion_point(field_release:Oreka.Dashboard.Gridcolumndata.field)
  return _impl_.field_.Release();
}
inline void Dashboard_Gridcolumndata::set_allocated_field(std::string* value) {
  _impl_.field_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.field_.IsDefault()) {
          _impl_.field_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.Dashboard.Gridcolumndata.field)
}

// string type = 2;
inline void Dashboard_Gridcolumndata::clear_type() {
  _impl_.type_.ClearToEmpty();
}
inline const std::string& Dashboard_Gridcolumndata::type() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Gridcolumndata.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Dashboard_Gridcolumndata::set_type(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.Gridcolumndata.type)
}
inline std::string* Dashboard_Gridcolumndata::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:Oreka.Dashboard.Gridcolumndata.type)
  return _s;
}
inline const std::string& Dashboard_Gridcolumndata::_internal_type() const {
  return _impl_.type_.Get();
}
inline void Dashboard_Gridcolumndata::_internal_set_type(const std::string& value) {
  ;


  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* Dashboard_Gridcolumndata::_internal_mutable_type() {
  ;
  return _impl_.type_.Mutable( GetArenaForAllocation());
}
inline std::string* Dashboard_Gridcolumndata::release_type() {
  // @@protoc_insertion_point(field_release:Oreka.Dashboard.Gridcolumndata.type)
  return _impl_.type_.Release();
}
inline void Dashboard_Gridcolumndata::set_allocated_type(std::string* value) {
  _impl_.type_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.type_.IsDefault()) {
          _impl_.type_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.Dashboard.Gridcolumndata.type)
}

// .Oreka.Dashboard.Gridproperties gridProperties = 3;
inline bool Dashboard_Gridcolumndata::has_gridproperties() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.gridproperties_ != nullptr);
  return value;
}
inline void Dashboard_Gridcolumndata::clear_gridproperties() {
  if (_impl_.gridproperties_ != nullptr) _impl_.gridproperties_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Oreka::Dashboard_Gridproperties& Dashboard_Gridcolumndata::_internal_gridproperties() const {
  const ::Oreka::Dashboard_Gridproperties* p = _impl_.gridproperties_;
  return p != nullptr ? *p : reinterpret_cast<const ::Oreka::Dashboard_Gridproperties&>(
      ::Oreka::_Dashboard_Gridproperties_default_instance_);
}
inline const ::Oreka::Dashboard_Gridproperties& Dashboard_Gridcolumndata::gridproperties() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Gridcolumndata.gridProperties)
  return _internal_gridproperties();
}
inline void Dashboard_Gridcolumndata::unsafe_arena_set_allocated_gridproperties(
    ::Oreka::Dashboard_Gridproperties* gridproperties) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.gridproperties_);
  }
  _impl_.gridproperties_ = gridproperties;
  if (gridproperties) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Oreka.Dashboard.Gridcolumndata.gridProperties)
}
inline ::Oreka::Dashboard_Gridproperties* Dashboard_Gridcolumndata::release_gridproperties() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Oreka::Dashboard_Gridproperties* temp = _impl_.gridproperties_;
  _impl_.gridproperties_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Oreka::Dashboard_Gridproperties* Dashboard_Gridcolumndata::unsafe_arena_release_gridproperties() {
  // @@protoc_insertion_point(field_release:Oreka.Dashboard.Gridcolumndata.gridProperties)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Oreka::Dashboard_Gridproperties* temp = _impl_.gridproperties_;
  _impl_.gridproperties_ = nullptr;
  return temp;
}
inline ::Oreka::Dashboard_Gridproperties* Dashboard_Gridcolumndata::_internal_mutable_gridproperties() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.gridproperties_ == nullptr) {
    auto* p = CreateMaybeMessage<::Oreka::Dashboard_Gridproperties>(GetArenaForAllocation());
    _impl_.gridproperties_ = p;
  }
  return _impl_.gridproperties_;
}
inline ::Oreka::Dashboard_Gridproperties* Dashboard_Gridcolumndata::mutable_gridproperties() {
  ::Oreka::Dashboard_Gridproperties* _msg = _internal_mutable_gridproperties();
  // @@protoc_insertion_point(field_mutable:Oreka.Dashboard.Gridcolumndata.gridProperties)
  return _msg;
}
inline void Dashboard_Gridcolumndata::set_allocated_gridproperties(::Oreka::Dashboard_Gridproperties* gridproperties) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.gridproperties_;
  }
  if (gridproperties) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(gridproperties);
    if (message_arena != submessage_arena) {
      gridproperties = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, gridproperties, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.gridproperties_ = gridproperties;
  // @@protoc_insertion_point(field_set_allocated:Oreka.Dashboard.Gridcolumndata.gridProperties)
}

// repeated .Oreka.Dashboard.Data data = 4;
inline int Dashboard_Gridcolumndata::_internal_data_size() const {
  return _impl_.data_.size();
}
inline int Dashboard_Gridcolumndata::data_size() const {
  return _internal_data_size();
}
inline void Dashboard_Gridcolumndata::clear_data() {
  _internal_mutable_data()->Clear();
}
inline ::Oreka::Dashboard_Data* Dashboard_Gridcolumndata::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:Oreka.Dashboard.Gridcolumndata.data)
  return _internal_mutable_data()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::Dashboard_Data >*
Dashboard_Gridcolumndata::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:Oreka.Dashboard.Gridcolumndata.data)
  return _internal_mutable_data();
}
inline const ::Oreka::Dashboard_Data& Dashboard_Gridcolumndata::_internal_data(int index) const {
  return _internal_data().Get(index);
}
inline const ::Oreka::Dashboard_Data& Dashboard_Gridcolumndata::data(int index) const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.Gridcolumndata.data)
  return _internal_data(index);
}
inline ::Oreka::Dashboard_Data* Dashboard_Gridcolumndata::_internal_add_data() {
  return _internal_mutable_data()->Add();
}
inline ::Oreka::Dashboard_Data* Dashboard_Gridcolumndata::add_data() {
  ::Oreka::Dashboard_Data* _add = _internal_add_data();
  // @@protoc_insertion_point(field_add:Oreka.Dashboard.Gridcolumndata.data)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::Dashboard_Data >&
Dashboard_Gridcolumndata::data() const {
  // @@protoc_insertion_point(field_list:Oreka.Dashboard.Gridcolumndata.data)
  return _internal_data();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::Dashboard_Data>&
Dashboard_Gridcolumndata::_internal_data() const {
  return _impl_.data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::Dashboard_Data>*
Dashboard_Gridcolumndata::_internal_mutable_data() {
  return &_impl_.data_;
}

// -------------------------------------------------------------------

// Dashboard

// string type = 1;
inline void Dashboard::clear_type() {
  _impl_.type_.ClearToEmpty();
}
inline const std::string& Dashboard::type() const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Dashboard::set_type(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.Dashboard.type)
}
inline std::string* Dashboard::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:Oreka.Dashboard.type)
  return _s;
}
inline const std::string& Dashboard::_internal_type() const {
  return _impl_.type_.Get();
}
inline void Dashboard::_internal_set_type(const std::string& value) {
  ;


  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* Dashboard::_internal_mutable_type() {
  ;
  return _impl_.type_.Mutable( GetArenaForAllocation());
}
inline std::string* Dashboard::release_type() {
  // @@protoc_insertion_point(field_release:Oreka.Dashboard.type)
  return _impl_.type_.Release();
}
inline void Dashboard::set_allocated_type(std::string* value) {
  _impl_.type_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.type_.IsDefault()) {
          _impl_.type_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.Dashboard.type)
}

// repeated .Oreka.Dashboard.Gridcolumndata gridcolumndata = 2;
inline int Dashboard::_internal_gridcolumndata_size() const {
  return _impl_.gridcolumndata_.size();
}
inline int Dashboard::gridcolumndata_size() const {
  return _internal_gridcolumndata_size();
}
inline void Dashboard::clear_gridcolumndata() {
  _internal_mutable_gridcolumndata()->Clear();
}
inline ::Oreka::Dashboard_Gridcolumndata* Dashboard::mutable_gridcolumndata(int index) {
  // @@protoc_insertion_point(field_mutable:Oreka.Dashboard.gridcolumndata)
  return _internal_mutable_gridcolumndata()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::Dashboard_Gridcolumndata >*
Dashboard::mutable_gridcolumndata() {
  // @@protoc_insertion_point(field_mutable_list:Oreka.Dashboard.gridcolumndata)
  return _internal_mutable_gridcolumndata();
}
inline const ::Oreka::Dashboard_Gridcolumndata& Dashboard::_internal_gridcolumndata(int index) const {
  return _internal_gridcolumndata().Get(index);
}
inline const ::Oreka::Dashboard_Gridcolumndata& Dashboard::gridcolumndata(int index) const {
  // @@protoc_insertion_point(field_get:Oreka.Dashboard.gridcolumndata)
  return _internal_gridcolumndata(index);
}
inline ::Oreka::Dashboard_Gridcolumndata* Dashboard::_internal_add_gridcolumndata() {
  return _internal_mutable_gridcolumndata()->Add();
}
inline ::Oreka::Dashboard_Gridcolumndata* Dashboard::add_gridcolumndata() {
  ::Oreka::Dashboard_Gridcolumndata* _add = _internal_add_gridcolumndata();
  // @@protoc_insertion_point(field_add:Oreka.Dashboard.gridcolumndata)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::Dashboard_Gridcolumndata >&
Dashboard::gridcolumndata() const {
  // @@protoc_insertion_point(field_list:Oreka.Dashboard.gridcolumndata)
  return _internal_gridcolumndata();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::Dashboard_Gridcolumndata>&
Dashboard::_internal_gridcolumndata() const {
  return _impl_.gridcolumndata_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::Dashboard_Gridcolumndata>*
Dashboard::_internal_mutable_gridcolumndata() {
  return &_impl_.gridcolumndata_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Oreka


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Dashboard_2eproto_2epb_2eh
