// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DealTransferRequest.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DealTransferRequest_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_DealTransferRequest_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_DealTransferRequest_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DealTransferRequest_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_DealTransferRequest_2eproto;
namespace Oreka {
class DealTransferRequest;
struct DealTransferRequestDefaultTypeInternal;
extern DealTransferRequestDefaultTypeInternal _DealTransferRequest_default_instance_;
}  // namespace Oreka
PROTOBUF_NAMESPACE_OPEN
template <>
::Oreka::DealTransferRequest* Arena::CreateMaybeMessage<::Oreka::DealTransferRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace Oreka {

// ===================================================================


// -------------------------------------------------------------------

class DealTransferRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Oreka.DealTransferRequest) */ {
 public:
  inline DealTransferRequest() : DealTransferRequest(nullptr) {}
  ~DealTransferRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR DealTransferRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DealTransferRequest(const DealTransferRequest& from);
  DealTransferRequest(DealTransferRequest&& from) noexcept
    : DealTransferRequest() {
    *this = ::std::move(from);
  }

  inline DealTransferRequest& operator=(const DealTransferRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DealTransferRequest& operator=(DealTransferRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DealTransferRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DealTransferRequest* internal_default_instance() {
    return reinterpret_cast<const DealTransferRequest*>(
               &_DealTransferRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DealTransferRequest& a, DealTransferRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DealTransferRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DealTransferRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DealTransferRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DealTransferRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DealTransferRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DealTransferRequest& from) {
    DealTransferRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DealTransferRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Oreka.DealTransferRequest";
  }
  protected:
  explicit DealTransferRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGroupsFieldNumber = 2,
    kTypeFieldNumber = 1,
    kFilenameFieldNumber = 3,
  };
  // repeated string groups = 2;
  int groups_size() const;
  private:
  int _internal_groups_size() const;

  public:
  void clear_groups() ;
  const std::string& groups(int index) const;
  std::string* mutable_groups(int index);
  void set_groups(int index, const std::string& value);
  void set_groups(int index, std::string&& value);
  void set_groups(int index, const char* value);
  void set_groups(int index, const char* value, std::size_t size);
  void set_groups(int index, absl::string_view value);
  std::string* add_groups();
  void add_groups(const std::string& value);
  void add_groups(std::string&& value);
  void add_groups(const char* value);
  void add_groups(const char* value, std::size_t size);
  void add_groups(absl::string_view value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& groups() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_groups();

  private:
  const std::string& _internal_groups(int index) const;
  std::string* _internal_add_groups();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& _internal_groups() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* _internal_mutable_groups();

  public:
  // string type = 1;
  void clear_type() ;
  const std::string& type() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* ptr);

  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(
      const std::string& value);
  std::string* _internal_mutable_type();

  public:
  // string filename = 3;
  void clear_filename() ;
  const std::string& filename() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_filename(Arg_&& arg, Args_... args);
  std::string* mutable_filename();
  PROTOBUF_NODISCARD std::string* release_filename();
  void set_allocated_filename(std::string* ptr);

  private:
  const std::string& _internal_filename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename(
      const std::string& value);
  std::string* _internal_mutable_filename();

  public:
  // @@protoc_insertion_point(class_scope:Oreka.DealTransferRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> groups_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DealTransferRequest_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DealTransferRequest

// string type = 1;
inline void DealTransferRequest::clear_type() {
  _impl_.type_.ClearToEmpty();
}
inline const std::string& DealTransferRequest::type() const {
  // @@protoc_insertion_point(field_get:Oreka.DealTransferRequest.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DealTransferRequest::set_type(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.DealTransferRequest.type)
}
inline std::string* DealTransferRequest::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:Oreka.DealTransferRequest.type)
  return _s;
}
inline const std::string& DealTransferRequest::_internal_type() const {
  return _impl_.type_.Get();
}
inline void DealTransferRequest::_internal_set_type(const std::string& value) {
  ;


  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* DealTransferRequest::_internal_mutable_type() {
  ;
  return _impl_.type_.Mutable( GetArenaForAllocation());
}
inline std::string* DealTransferRequest::release_type() {
  // @@protoc_insertion_point(field_release:Oreka.DealTransferRequest.type)
  return _impl_.type_.Release();
}
inline void DealTransferRequest::set_allocated_type(std::string* value) {
  _impl_.type_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.type_.IsDefault()) {
          _impl_.type_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.DealTransferRequest.type)
}

// repeated string groups = 2;
inline int DealTransferRequest::_internal_groups_size() const {
  return _impl_.groups_.size();
}
inline int DealTransferRequest::groups_size() const {
  return _internal_groups_size();
}
inline void DealTransferRequest::clear_groups() {
  _internal_mutable_groups()->Clear();
}
inline std::string* DealTransferRequest::add_groups() {
  std::string* _s = _internal_add_groups();
  // @@protoc_insertion_point(field_add_mutable:Oreka.DealTransferRequest.groups)
  return _s;
}
inline const std::string& DealTransferRequest::groups(int index) const {
  // @@protoc_insertion_point(field_get:Oreka.DealTransferRequest.groups)
  return _internal_groups(index);
}
inline std::string* DealTransferRequest::mutable_groups(int index) {
  // @@protoc_insertion_point(field_mutable:Oreka.DealTransferRequest.groups)
  return _internal_mutable_groups()->Mutable(index);
}
inline void DealTransferRequest::set_groups(int index, const std::string& value) {
  _internal_mutable_groups()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:Oreka.DealTransferRequest.groups)
}
inline void DealTransferRequest::set_groups(int index, std::string&& value) {
  _internal_mutable_groups()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:Oreka.DealTransferRequest.groups)
}
inline void DealTransferRequest::set_groups(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_groups()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Oreka.DealTransferRequest.groups)
}
inline void DealTransferRequest::set_groups(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_groups()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Oreka.DealTransferRequest.groups)
}
inline void DealTransferRequest::set_groups(int index, absl::string_view value) {
  _internal_mutable_groups()->Mutable(index)->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_set_string_piece:Oreka.DealTransferRequest.groups)
}
inline void DealTransferRequest::add_groups(const std::string& value) {
  _internal_mutable_groups()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:Oreka.DealTransferRequest.groups)
}
inline void DealTransferRequest::add_groups(std::string&& value) {
  _internal_mutable_groups()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:Oreka.DealTransferRequest.groups)
}
inline void DealTransferRequest::add_groups(const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_groups()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Oreka.DealTransferRequest.groups)
}
inline void DealTransferRequest::add_groups(const char* value, std::size_t size) {
  _internal_mutable_groups()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Oreka.DealTransferRequest.groups)
}
inline void DealTransferRequest::add_groups(absl::string_view value) {
  _internal_mutable_groups()->Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:Oreka.DealTransferRequest.groups)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
DealTransferRequest::groups() const {
  // @@protoc_insertion_point(field_list:Oreka.DealTransferRequest.groups)
  return _internal_groups();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* DealTransferRequest::mutable_groups() {
  // @@protoc_insertion_point(field_mutable_list:Oreka.DealTransferRequest.groups)
  return _internal_mutable_groups();
}
inline const std::string& DealTransferRequest::_internal_groups(int index) const {
  return _internal_groups().Get(index);
}
inline std::string* DealTransferRequest::_internal_add_groups() {
  return _internal_mutable_groups()->Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
DealTransferRequest::_internal_groups() const {
  return _impl_.groups_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
DealTransferRequest::_internal_mutable_groups() {
  return &_impl_.groups_;
}

// string filename = 3;
inline void DealTransferRequest::clear_filename() {
  _impl_.filename_.ClearToEmpty();
}
inline const std::string& DealTransferRequest::filename() const {
  // @@protoc_insertion_point(field_get:Oreka.DealTransferRequest.filename)
  return _internal_filename();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DealTransferRequest::set_filename(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.filename_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.DealTransferRequest.filename)
}
inline std::string* DealTransferRequest::mutable_filename() {
  std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:Oreka.DealTransferRequest.filename)
  return _s;
}
inline const std::string& DealTransferRequest::_internal_filename() const {
  return _impl_.filename_.Get();
}
inline void DealTransferRequest::_internal_set_filename(const std::string& value) {
  ;


  _impl_.filename_.Set(value, GetArenaForAllocation());
}
inline std::string* DealTransferRequest::_internal_mutable_filename() {
  ;
  return _impl_.filename_.Mutable( GetArenaForAllocation());
}
inline std::string* DealTransferRequest::release_filename() {
  // @@protoc_insertion_point(field_release:Oreka.DealTransferRequest.filename)
  return _impl_.filename_.Release();
}
inline void DealTransferRequest::set_allocated_filename(std::string* value) {
  _impl_.filename_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.filename_.IsDefault()) {
          _impl_.filename_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.DealTransferRequest.filename)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Oreka


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_DealTransferRequest_2eproto_2epb_2eh
