// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DealingDataInterval.proto
#include "stdafx.h"
#include "DealingDataInterval.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace Oreka {
template <typename>
PROTOBUF_CONSTEXPR DealingDataInterval_Dealingdata::DealingDataInterval_Dealingdata(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.login_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.symbol_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.buysell_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.reason_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.dealingtype_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.subscriptionid_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.id_)*/ 0u

  , /*decltype(_impl_.time_)*/ 0u

  , /*decltype(_impl_.volume_)*/ 0

  , /*decltype(_impl_.price_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DealingDataInterval_DealingdataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DealingDataInterval_DealingdataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DealingDataInterval_DealingdataDefaultTypeInternal() {}
  union {
    DealingDataInterval_Dealingdata _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DealingDataInterval_DealingdataDefaultTypeInternal _DealingDataInterval_Dealingdata_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR DealingDataInterval::DealingDataInterval(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.dealingdata_)*/{}
  , /*decltype(_impl_.type_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.subscriptionid_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DealingDataIntervalDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DealingDataIntervalDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DealingDataIntervalDefaultTypeInternal() {}
  union {
    DealingDataInterval _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DealingDataIntervalDefaultTypeInternal _DealingDataInterval_default_instance_;
}  // namespace Oreka
static ::_pb::Metadata file_level_metadata_DealingDataInterval_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_DealingDataInterval_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_DealingDataInterval_2eproto = nullptr;
const ::uint32_t TableStruct_DealingDataInterval_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval_Dealingdata, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval_Dealingdata, _impl_.type_),
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval_Dealingdata, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval_Dealingdata, _impl_.time_),
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval_Dealingdata, _impl_.login_),
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval_Dealingdata, _impl_.symbol_),
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval_Dealingdata, _impl_.buysell_),
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval_Dealingdata, _impl_.volume_),
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval_Dealingdata, _impl_.price_),
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval_Dealingdata, _impl_.reason_),
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval_Dealingdata, _impl_.dealingtype_),
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval_Dealingdata, _impl_.subscriptionid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval, _impl_.type_),
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval, _impl_.subscriptionid_),
    PROTOBUF_FIELD_OFFSET(::Oreka::DealingDataInterval, _impl_.dealingdata_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::Oreka::DealingDataInterval_Dealingdata)},
        { 19, -1, -1, sizeof(::Oreka::DealingDataInterval)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::Oreka::_DealingDataInterval_Dealingdata_default_instance_._instance,
    &::Oreka::_DealingDataInterval_default_instance_._instance,
};
const char descriptor_table_protodef_DealingDataInterval_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\031DealingDataInterval.proto\022\005Oreka\"\274\002\n\023D"
    "ealingDataInterval\022\014\n\004type\030\001 \001(\t\022\026\n\016subs"
    "criptionId\030\002 \001(\t\022;\n\013dealingData\030\003 \003(\0132&."
    "Oreka.DealingDataInterval.Dealingdata\032\301\001"
    "\n\013Dealingdata\022\014\n\004type\030\001 \001(\t\022\n\n\002id\030\002 \001(\r\022"
    "\014\n\004time\030\003 \001(\r\022\r\n\005login\030\004 \001(\t\022\016\n\006symbol\030\005"
    " \001(\t\022\017\n\007buysell\030\006 \001(\t\022\016\n\006volume\030\007 \001(\001\022\r\n"
    "\005price\030\010 \001(\001\022\016\n\006reason\030\t \001(\t\022\023\n\013dealingt"
    "ype\030\n \001(\t\022\026\n\016subscriptionId\030\013 \001(\tb\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_DealingDataInterval_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_DealingDataInterval_2eproto = {
    false,
    false,
    361,
    descriptor_table_protodef_DealingDataInterval_2eproto,
    "DealingDataInterval.proto",
    &descriptor_table_DealingDataInterval_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_DealingDataInterval_2eproto::offsets,
    file_level_metadata_DealingDataInterval_2eproto,
    file_level_enum_descriptors_DealingDataInterval_2eproto,
    file_level_service_descriptors_DealingDataInterval_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_DealingDataInterval_2eproto_getter() {
  return &descriptor_table_DealingDataInterval_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_DealingDataInterval_2eproto(&descriptor_table_DealingDataInterval_2eproto);
namespace Oreka {
// ===================================================================

class DealingDataInterval_Dealingdata::_Internal {
 public:
};

DealingDataInterval_Dealingdata::DealingDataInterval_Dealingdata(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Oreka.DealingDataInterval.Dealingdata)
}
DealingDataInterval_Dealingdata::DealingDataInterval_Dealingdata(const DealingDataInterval_Dealingdata& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DealingDataInterval_Dealingdata* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_) {}

    , decltype(_impl_.login_) {}

    , decltype(_impl_.symbol_) {}

    , decltype(_impl_.buysell_) {}

    , decltype(_impl_.reason_) {}

    , decltype(_impl_.dealingtype_) {}

    , decltype(_impl_.subscriptionid_) {}

    , decltype(_impl_.id_) {}

    , decltype(_impl_.time_) {}

    , decltype(_impl_.volume_) {}

    , decltype(_impl_.price_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_type().empty()) {
    _this->_impl_.type_.Set(from._internal_type(), _this->GetArenaForAllocation());
  }
  _impl_.login_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.login_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_login().empty()) {
    _this->_impl_.login_.Set(from._internal_login(), _this->GetArenaForAllocation());
  }
  _impl_.symbol_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.symbol_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_symbol().empty()) {
    _this->_impl_.symbol_.Set(from._internal_symbol(), _this->GetArenaForAllocation());
  }
  _impl_.buysell_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.buysell_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_buysell().empty()) {
    _this->_impl_.buysell_.Set(from._internal_buysell(), _this->GetArenaForAllocation());
  }
  _impl_.reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.reason_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_reason().empty()) {
    _this->_impl_.reason_.Set(from._internal_reason(), _this->GetArenaForAllocation());
  }
  _impl_.dealingtype_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.dealingtype_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_dealingtype().empty()) {
    _this->_impl_.dealingtype_.Set(from._internal_dealingtype(), _this->GetArenaForAllocation());
  }
  _impl_.subscriptionid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.subscriptionid_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_subscriptionid().empty()) {
    _this->_impl_.subscriptionid_.Set(from._internal_subscriptionid(), _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.price_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.price_));
  // @@protoc_insertion_point(copy_constructor:Oreka.DealingDataInterval.Dealingdata)
}

inline void DealingDataInterval_Dealingdata::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.type_) {}

    , decltype(_impl_.login_) {}

    , decltype(_impl_.symbol_) {}

    , decltype(_impl_.buysell_) {}

    , decltype(_impl_.reason_) {}

    , decltype(_impl_.dealingtype_) {}

    , decltype(_impl_.subscriptionid_) {}

    , decltype(_impl_.id_) { 0u }

    , decltype(_impl_.time_) { 0u }

    , decltype(_impl_.volume_) { 0 }

    , decltype(_impl_.price_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.login_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.login_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.symbol_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.symbol_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.buysell_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.buysell_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.reason_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.dealingtype_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.dealingtype_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.subscriptionid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.subscriptionid_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DealingDataInterval_Dealingdata::~DealingDataInterval_Dealingdata() {
  // @@protoc_insertion_point(destructor:Oreka.DealingDataInterval.Dealingdata)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DealingDataInterval_Dealingdata::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.type_.Destroy();
  _impl_.login_.Destroy();
  _impl_.symbol_.Destroy();
  _impl_.buysell_.Destroy();
  _impl_.reason_.Destroy();
  _impl_.dealingtype_.Destroy();
  _impl_.subscriptionid_.Destroy();
}

void DealingDataInterval_Dealingdata::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DealingDataInterval_Dealingdata::Clear() {
// @@protoc_insertion_point(message_clear_start:Oreka.DealingDataInterval.Dealingdata)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_.ClearToEmpty();
  _impl_.login_.ClearToEmpty();
  _impl_.symbol_.ClearToEmpty();
  _impl_.buysell_.ClearToEmpty();
  _impl_.reason_.ClearToEmpty();
  _impl_.dealingtype_.ClearToEmpty();
  _impl_.subscriptionid_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.price_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.price_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DealingDataInterval_Dealingdata::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.DealingDataInterval.Dealingdata.type"));
        } else {
          goto handle_unusual;
        }
        continue;
      // uint32 id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // uint32 time = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 24)) {
          _impl_.time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // string login = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_login();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.DealingDataInterval.Dealingdata.login"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string symbol = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_symbol();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.DealingDataInterval.Dealingdata.symbol"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string buysell = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_buysell();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.DealingDataInterval.Dealingdata.buysell"));
        } else {
          goto handle_unusual;
        }
        continue;
      // double volume = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 57)) {
          _impl_.volume_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // double price = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 65)) {
          _impl_.price_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // string reason = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_reason();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.DealingDataInterval.Dealingdata.reason"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string dealingtype = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_dealingtype();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.DealingDataInterval.Dealingdata.dealingtype"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string subscriptionId = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_subscriptionid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.DealingDataInterval.Dealingdata.subscriptionId"));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* DealingDataInterval_Dealingdata::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Oreka.DealingDataInterval.Dealingdata)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (!this->_internal_type().empty()) {
    const std::string& _s = this->_internal_type();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.DealingDataInterval.Dealingdata.type");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // uint32 id = 2;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_id(), target);
  }

  // uint32 time = 3;
  if (this->_internal_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_time(), target);
  }

  // string login = 4;
  if (!this->_internal_login().empty()) {
    const std::string& _s = this->_internal_login();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.DealingDataInterval.Dealingdata.login");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // string symbol = 5;
  if (!this->_internal_symbol().empty()) {
    const std::string& _s = this->_internal_symbol();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.DealingDataInterval.Dealingdata.symbol");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // string buysell = 6;
  if (!this->_internal_buysell().empty()) {
    const std::string& _s = this->_internal_buysell();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.DealingDataInterval.Dealingdata.buysell");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  // double volume = 7;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_volume = this->_internal_volume();
  ::uint64_t raw_volume;
  memcpy(&raw_volume, &tmp_volume, sizeof(tmp_volume));
  if (raw_volume != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        7, this->_internal_volume(), target);
  }

  // double price = 8;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_price = this->_internal_price();
  ::uint64_t raw_price;
  memcpy(&raw_price, &tmp_price, sizeof(tmp_price));
  if (raw_price != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        8, this->_internal_price(), target);
  }

  // string reason = 9;
  if (!this->_internal_reason().empty()) {
    const std::string& _s = this->_internal_reason();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.DealingDataInterval.Dealingdata.reason");
    target = stream->WriteStringMaybeAliased(9, _s, target);
  }

  // string dealingtype = 10;
  if (!this->_internal_dealingtype().empty()) {
    const std::string& _s = this->_internal_dealingtype();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.DealingDataInterval.Dealingdata.dealingtype");
    target = stream->WriteStringMaybeAliased(10, _s, target);
  }

  // string subscriptionId = 11;
  if (!this->_internal_subscriptionid().empty()) {
    const std::string& _s = this->_internal_subscriptionid();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.DealingDataInterval.Dealingdata.subscriptionId");
    target = stream->WriteStringMaybeAliased(11, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Oreka.DealingDataInterval.Dealingdata)
  return target;
}

::size_t DealingDataInterval_Dealingdata::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Oreka.DealingDataInterval.Dealingdata)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string type = 1;
  if (!this->_internal_type().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_type());
  }

  // string login = 4;
  if (!this->_internal_login().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_login());
  }

  // string symbol = 5;
  if (!this->_internal_symbol().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_symbol());
  }

  // string buysell = 6;
  if (!this->_internal_buysell().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_buysell());
  }

  // string reason = 9;
  if (!this->_internal_reason().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_reason());
  }

  // string dealingtype = 10;
  if (!this->_internal_dealingtype().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_dealingtype());
  }

  // string subscriptionId = 11;
  if (!this->_internal_subscriptionid().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_subscriptionid());
  }

  // uint32 id = 2;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_id());
  }

  // uint32 time = 3;
  if (this->_internal_time() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_time());
  }

  // double volume = 7;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_volume = this->_internal_volume();
  ::uint64_t raw_volume;
  memcpy(&raw_volume, &tmp_volume, sizeof(tmp_volume));
  if (raw_volume != 0) {
    total_size += 9;
  }

  // double price = 8;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_price = this->_internal_price();
  ::uint64_t raw_price;
  memcpy(&raw_price, &tmp_price, sizeof(tmp_price));
  if (raw_price != 0) {
    total_size += 9;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DealingDataInterval_Dealingdata::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DealingDataInterval_Dealingdata::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DealingDataInterval_Dealingdata::GetClassData() const { return &_class_data_; }


void DealingDataInterval_Dealingdata::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DealingDataInterval_Dealingdata*>(&to_msg);
  auto& from = static_cast<const DealingDataInterval_Dealingdata&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Oreka.DealingDataInterval.Dealingdata)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  if (!from._internal_login().empty()) {
    _this->_internal_set_login(from._internal_login());
  }
  if (!from._internal_symbol().empty()) {
    _this->_internal_set_symbol(from._internal_symbol());
  }
  if (!from._internal_buysell().empty()) {
    _this->_internal_set_buysell(from._internal_buysell());
  }
  if (!from._internal_reason().empty()) {
    _this->_internal_set_reason(from._internal_reason());
  }
  if (!from._internal_dealingtype().empty()) {
    _this->_internal_set_dealingtype(from._internal_dealingtype());
  }
  if (!from._internal_subscriptionid().empty()) {
    _this->_internal_set_subscriptionid(from._internal_subscriptionid());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_time() != 0) {
    _this->_internal_set_time(from._internal_time());
  }
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_volume = from._internal_volume();
  ::uint64_t raw_volume;
  memcpy(&raw_volume, &tmp_volume, sizeof(tmp_volume));
  if (raw_volume != 0) {
    _this->_internal_set_volume(from._internal_volume());
  }
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_price = from._internal_price();
  ::uint64_t raw_price;
  memcpy(&raw_price, &tmp_price, sizeof(tmp_price));
  if (raw_price != 0) {
    _this->_internal_set_price(from._internal_price());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DealingDataInterval_Dealingdata::CopyFrom(const DealingDataInterval_Dealingdata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Oreka.DealingDataInterval.Dealingdata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DealingDataInterval_Dealingdata::IsInitialized() const {
  return true;
}

void DealingDataInterval_Dealingdata::InternalSwap(DealingDataInterval_Dealingdata* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_, lhs_arena,
                                       &other->_impl_.type_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.login_, lhs_arena,
                                       &other->_impl_.login_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.symbol_, lhs_arena,
                                       &other->_impl_.symbol_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.buysell_, lhs_arena,
                                       &other->_impl_.buysell_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reason_, lhs_arena,
                                       &other->_impl_.reason_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.dealingtype_, lhs_arena,
                                       &other->_impl_.dealingtype_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.subscriptionid_, lhs_arena,
                                       &other->_impl_.subscriptionid_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DealingDataInterval_Dealingdata, _impl_.price_)
      + sizeof(DealingDataInterval_Dealingdata::_impl_.price_)
      - PROTOBUF_FIELD_OFFSET(DealingDataInterval_Dealingdata, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DealingDataInterval_Dealingdata::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_DealingDataInterval_2eproto_getter, &descriptor_table_DealingDataInterval_2eproto_once,
      file_level_metadata_DealingDataInterval_2eproto[0]);
}
// ===================================================================

class DealingDataInterval::_Internal {
 public:
};

DealingDataInterval::DealingDataInterval(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Oreka.DealingDataInterval)
}
DealingDataInterval::DealingDataInterval(const DealingDataInterval& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DealingDataInterval* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.dealingdata_){from._impl_.dealingdata_}
    , decltype(_impl_.type_) {}

    , decltype(_impl_.subscriptionid_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_type().empty()) {
    _this->_impl_.type_.Set(from._internal_type(), _this->GetArenaForAllocation());
  }
  _impl_.subscriptionid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.subscriptionid_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_subscriptionid().empty()) {
    _this->_impl_.subscriptionid_.Set(from._internal_subscriptionid(), _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:Oreka.DealingDataInterval)
}

inline void DealingDataInterval::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.dealingdata_){arena}
    , decltype(_impl_.type_) {}

    , decltype(_impl_.subscriptionid_) {}

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.subscriptionid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.subscriptionid_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DealingDataInterval::~DealingDataInterval() {
  // @@protoc_insertion_point(destructor:Oreka.DealingDataInterval)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DealingDataInterval::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _internal_mutable_dealingdata()->~RepeatedPtrField();
  _impl_.type_.Destroy();
  _impl_.subscriptionid_.Destroy();
}

void DealingDataInterval::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DealingDataInterval::Clear() {
// @@protoc_insertion_point(message_clear_start:Oreka.DealingDataInterval)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_dealingdata()->Clear();
  _impl_.type_.ClearToEmpty();
  _impl_.subscriptionid_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DealingDataInterval::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.DealingDataInterval.type"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string subscriptionId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_subscriptionid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.DealingDataInterval.subscriptionId"));
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated .Oreka.DealingDataInterval.Dealingdata dealingData = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_dealingdata(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* DealingDataInterval::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Oreka.DealingDataInterval)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (!this->_internal_type().empty()) {
    const std::string& _s = this->_internal_type();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.DealingDataInterval.type");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string subscriptionId = 2;
  if (!this->_internal_subscriptionid().empty()) {
    const std::string& _s = this->_internal_subscriptionid();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.DealingDataInterval.subscriptionId");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // repeated .Oreka.DealingDataInterval.Dealingdata dealingData = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_dealingdata_size()); i < n; i++) {
    const auto& repfield = this->_internal_dealingdata(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Oreka.DealingDataInterval)
  return target;
}

::size_t DealingDataInterval::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Oreka.DealingDataInterval)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Oreka.DealingDataInterval.Dealingdata dealingData = 3;
  total_size += 1UL * this->_internal_dealingdata_size();
  for (const auto& msg : this->_internal_dealingdata()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string type = 1;
  if (!this->_internal_type().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_type());
  }

  // string subscriptionId = 2;
  if (!this->_internal_subscriptionid().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_subscriptionid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DealingDataInterval::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DealingDataInterval::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DealingDataInterval::GetClassData() const { return &_class_data_; }


void DealingDataInterval::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DealingDataInterval*>(&to_msg);
  auto& from = static_cast<const DealingDataInterval&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Oreka.DealingDataInterval)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_dealingdata()->MergeFrom(from._internal_dealingdata());
  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  if (!from._internal_subscriptionid().empty()) {
    _this->_internal_set_subscriptionid(from._internal_subscriptionid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DealingDataInterval::CopyFrom(const DealingDataInterval& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Oreka.DealingDataInterval)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DealingDataInterval::IsInitialized() const {
  return true;
}

void DealingDataInterval::InternalSwap(DealingDataInterval* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _internal_mutable_dealingdata()->InternalSwap(other->_internal_mutable_dealingdata());
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_, lhs_arena,
                                       &other->_impl_.type_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.subscriptionid_, lhs_arena,
                                       &other->_impl_.subscriptionid_, rhs_arena);
}

::PROTOBUF_NAMESPACE_ID::Metadata DealingDataInterval::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_DealingDataInterval_2eproto_getter, &descriptor_table_DealingDataInterval_2eproto_once,
      file_level_metadata_DealingDataInterval_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Oreka
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Oreka::DealingDataInterval_Dealingdata*
Arena::CreateMaybeMessage< ::Oreka::DealingDataInterval_Dealingdata >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Oreka::DealingDataInterval_Dealingdata >(arena);
}
template<> PROTOBUF_NOINLINE ::Oreka::DealingDataInterval*
Arena::CreateMaybeMessage< ::Oreka::DealingDataInterval >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Oreka::DealingDataInterval >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
