// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeleteColorTheme.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DeleteColorTheme_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_DeleteColorTheme_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_DeleteColorTheme_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DeleteColorTheme_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_DeleteColorTheme_2eproto;
namespace Oreka {
class DeleteColorTheme;
struct DeleteColorThemeDefaultTypeInternal;
extern DeleteColorThemeDefaultTypeInternal _DeleteColorTheme_default_instance_;
}  // namespace Oreka
PROTOBUF_NAMESPACE_OPEN
template <>
::Oreka::DeleteColorTheme* Arena::CreateMaybeMessage<::Oreka::DeleteColorTheme>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace Oreka {

// ===================================================================


// -------------------------------------------------------------------

class DeleteColorTheme final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Oreka.DeleteColorTheme) */ {
 public:
  inline DeleteColorTheme() : DeleteColorTheme(nullptr) {}
  ~DeleteColorTheme() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR DeleteColorTheme(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DeleteColorTheme(const DeleteColorTheme& from);
  DeleteColorTheme(DeleteColorTheme&& from) noexcept
    : DeleteColorTheme() {
    *this = ::std::move(from);
  }

  inline DeleteColorTheme& operator=(const DeleteColorTheme& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeleteColorTheme& operator=(DeleteColorTheme&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DeleteColorTheme& default_instance() {
    return *internal_default_instance();
  }
  static inline const DeleteColorTheme* internal_default_instance() {
    return reinterpret_cast<const DeleteColorTheme*>(
               &_DeleteColorTheme_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DeleteColorTheme& a, DeleteColorTheme& b) {
    a.Swap(&b);
  }
  inline void Swap(DeleteColorTheme* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DeleteColorTheme* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DeleteColorTheme* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DeleteColorTheme>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DeleteColorTheme& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DeleteColorTheme& from) {
    DeleteColorTheme::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeleteColorTheme* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Oreka.DeleteColorTheme";
  }
  protected:
  explicit DeleteColorTheme(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kIdFieldNumber = 2,
    kLoginUserFieldNumber = 3,
  };
  // string type = 1;
  void clear_type() ;
  const std::string& type() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* ptr);

  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(
      const std::string& value);
  std::string* _internal_mutable_type();

  public:
  // string id = 2;
  void clear_id() ;
  const std::string& id() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* ptr);

  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(
      const std::string& value);
  std::string* _internal_mutable_id();

  public:
  // string loginUser = 3;
  void clear_loginuser() ;
  const std::string& loginuser() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_loginuser(Arg_&& arg, Args_... args);
  std::string* mutable_loginuser();
  PROTOBUF_NODISCARD std::string* release_loginuser();
  void set_allocated_loginuser(std::string* ptr);

  private:
  const std::string& _internal_loginuser() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_loginuser(
      const std::string& value);
  std::string* _internal_mutable_loginuser();

  public:
  // @@protoc_insertion_point(class_scope:Oreka.DeleteColorTheme)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr loginuser_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DeleteColorTheme_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DeleteColorTheme

// string type = 1;
inline void DeleteColorTheme::clear_type() {
  _impl_.type_.ClearToEmpty();
}
inline const std::string& DeleteColorTheme::type() const {
  // @@protoc_insertion_point(field_get:Oreka.DeleteColorTheme.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DeleteColorTheme::set_type(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.DeleteColorTheme.type)
}
inline std::string* DeleteColorTheme::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:Oreka.DeleteColorTheme.type)
  return _s;
}
inline const std::string& DeleteColorTheme::_internal_type() const {
  return _impl_.type_.Get();
}
inline void DeleteColorTheme::_internal_set_type(const std::string& value) {
  ;


  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* DeleteColorTheme::_internal_mutable_type() {
  ;
  return _impl_.type_.Mutable( GetArenaForAllocation());
}
inline std::string* DeleteColorTheme::release_type() {
  // @@protoc_insertion_point(field_release:Oreka.DeleteColorTheme.type)
  return _impl_.type_.Release();
}
inline void DeleteColorTheme::set_allocated_type(std::string* value) {
  _impl_.type_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.type_.IsDefault()) {
          _impl_.type_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.DeleteColorTheme.type)
}

// string id = 2;
inline void DeleteColorTheme::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& DeleteColorTheme::id() const {
  // @@protoc_insertion_point(field_get:Oreka.DeleteColorTheme.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DeleteColorTheme::set_id(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.DeleteColorTheme.id)
}
inline std::string* DeleteColorTheme::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:Oreka.DeleteColorTheme.id)
  return _s;
}
inline const std::string& DeleteColorTheme::_internal_id() const {
  return _impl_.id_.Get();
}
inline void DeleteColorTheme::_internal_set_id(const std::string& value) {
  ;


  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* DeleteColorTheme::_internal_mutable_id() {
  ;
  return _impl_.id_.Mutable( GetArenaForAllocation());
}
inline std::string* DeleteColorTheme::release_id() {
  // @@protoc_insertion_point(field_release:Oreka.DeleteColorTheme.id)
  return _impl_.id_.Release();
}
inline void DeleteColorTheme::set_allocated_id(std::string* value) {
  _impl_.id_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.id_.IsDefault()) {
          _impl_.id_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.DeleteColorTheme.id)
}

// string loginUser = 3;
inline void DeleteColorTheme::clear_loginuser() {
  _impl_.loginuser_.ClearToEmpty();
}
inline const std::string& DeleteColorTheme::loginuser() const {
  // @@protoc_insertion_point(field_get:Oreka.DeleteColorTheme.loginUser)
  return _internal_loginuser();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DeleteColorTheme::set_loginuser(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.loginuser_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.DeleteColorTheme.loginUser)
}
inline std::string* DeleteColorTheme::mutable_loginuser() {
  std::string* _s = _internal_mutable_loginuser();
  // @@protoc_insertion_point(field_mutable:Oreka.DeleteColorTheme.loginUser)
  return _s;
}
inline const std::string& DeleteColorTheme::_internal_loginuser() const {
  return _impl_.loginuser_.Get();
}
inline void DeleteColorTheme::_internal_set_loginuser(const std::string& value) {
  ;


  _impl_.loginuser_.Set(value, GetArenaForAllocation());
}
inline std::string* DeleteColorTheme::_internal_mutable_loginuser() {
  ;
  return _impl_.loginuser_.Mutable( GetArenaForAllocation());
}
inline std::string* DeleteColorTheme::release_loginuser() {
  // @@protoc_insertion_point(field_release:Oreka.DeleteColorTheme.loginUser)
  return _impl_.loginuser_.Release();
}
inline void DeleteColorTheme::set_allocated_loginuser(std::string* value) {
  _impl_.loginuser_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.loginuser_.IsDefault()) {
          _impl_.loginuser_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.DeleteColorTheme.loginUser)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Oreka


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_DeleteColorTheme_2eproto_2epb_2eh
