// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "stdafx.h"

#include "TotalNoOfData.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace Oreka {
template <typename>
PROTOBUF_CONSTEXPR TotalNoOfData::TotalNoOfData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.total_data_)*/ 0u

  , /*decltype(_impl_.total_order_)*/ 0u

  , /*decltype(_impl_.total_deal_)*/ 0u

  , /*decltype(_impl_.total_position_)*/ 0u

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TotalNoOfDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TotalNoOfDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TotalNoOfDataDefaultTypeInternal() {}
  union {
    TotalNoOfData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TotalNoOfDataDefaultTypeInternal _TotalNoOfData_default_instance_;
}  // namespace Oreka
static ::_pb::Metadata file_level_metadata_TotalNoOfData_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_TotalNoOfData_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_TotalNoOfData_2eproto = nullptr;
const ::uint32_t TableStruct_TotalNoOfData_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Oreka::TotalNoOfData, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Oreka::TotalNoOfData, _impl_.type_),
    PROTOBUF_FIELD_OFFSET(::Oreka::TotalNoOfData, _impl_.total_data_),
    PROTOBUF_FIELD_OFFSET(::Oreka::TotalNoOfData, _impl_.total_order_),
    PROTOBUF_FIELD_OFFSET(::Oreka::TotalNoOfData, _impl_.total_deal_),
    PROTOBUF_FIELD_OFFSET(::Oreka::TotalNoOfData, _impl_.total_position_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::Oreka::TotalNoOfData)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::Oreka::_TotalNoOfData_default_instance_._instance,
};
const char descriptor_table_protodef_TotalNoOfData_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\023TotalNoOfData.proto\022\005Oreka\"r\n\rTotalNoO"
    "fData\022\014\n\004type\030\001 \001(\t\022\022\n\nTOTAL_DATA\030\002 \001(\r\022"
    "\023\n\013TOTAL_ORDER\030\003 \001(\r\022\022\n\nTOTAL_DEAL\030\004 \001(\r"
    "\022\026\n\016TOTAL_POSITION\030\005 \001(\rb\006proto3"
};
static ::absl::once_flag descriptor_table_TotalNoOfData_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_TotalNoOfData_2eproto = {
    false,
    false,
    152,
    descriptor_table_protodef_TotalNoOfData_2eproto,
    "TotalNoOfData.proto",
    &descriptor_table_TotalNoOfData_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_TotalNoOfData_2eproto::offsets,
    file_level_metadata_TotalNoOfData_2eproto,
    file_level_enum_descriptors_TotalNoOfData_2eproto,
    file_level_service_descriptors_TotalNoOfData_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_TotalNoOfData_2eproto_getter() {
  return &descriptor_table_TotalNoOfData_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_TotalNoOfData_2eproto(&descriptor_table_TotalNoOfData_2eproto);
namespace Oreka {
// ===================================================================

class TotalNoOfData::_Internal {
 public:
};

TotalNoOfData::TotalNoOfData(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Oreka.TotalNoOfData)
}
TotalNoOfData::TotalNoOfData(const TotalNoOfData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TotalNoOfData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_) {}

    , decltype(_impl_.total_data_) {}

    , decltype(_impl_.total_order_) {}

    , decltype(_impl_.total_deal_) {}

    , decltype(_impl_.total_position_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_type().empty()) {
    _this->_impl_.type_.Set(from._internal_type(), _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.total_data_, &from._impl_.total_data_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.total_position_) -
    reinterpret_cast<char*>(&_impl_.total_data_)) + sizeof(_impl_.total_position_));
  // @@protoc_insertion_point(copy_constructor:Oreka.TotalNoOfData)
}

inline void TotalNoOfData::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.type_) {}

    , decltype(_impl_.total_data_) { 0u }

    , decltype(_impl_.total_order_) { 0u }

    , decltype(_impl_.total_deal_) { 0u }

    , decltype(_impl_.total_position_) { 0u }

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TotalNoOfData::~TotalNoOfData() {
  // @@protoc_insertion_point(destructor:Oreka.TotalNoOfData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TotalNoOfData::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.type_.Destroy();
}

void TotalNoOfData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TotalNoOfData::Clear() {
// @@protoc_insertion_point(message_clear_start:Oreka.TotalNoOfData)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_.ClearToEmpty();
  ::memset(&_impl_.total_data_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.total_position_) -
      reinterpret_cast<char*>(&_impl_.total_data_)) + sizeof(_impl_.total_position_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TotalNoOfData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.TotalNoOfData.type"));
        } else {
          goto handle_unusual;
        }
        continue;
      // uint32 TOTAL_DATA = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _impl_.total_data_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // uint32 TOTAL_ORDER = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 24)) {
          _impl_.total_order_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // uint32 TOTAL_DEAL = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 32)) {
          _impl_.total_deal_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // uint32 TOTAL_POSITION = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 40)) {
          _impl_.total_position_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* TotalNoOfData::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Oreka.TotalNoOfData)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (!this->_internal_type().empty()) {
    const std::string& _s = this->_internal_type();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.TotalNoOfData.type");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // uint32 TOTAL_DATA = 2;
  if (this->_internal_total_data() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_total_data(), target);
  }

  // uint32 TOTAL_ORDER = 3;
  if (this->_internal_total_order() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_total_order(), target);
  }

  // uint32 TOTAL_DEAL = 4;
  if (this->_internal_total_deal() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_total_deal(), target);
  }

  // uint32 TOTAL_POSITION = 5;
  if (this->_internal_total_position() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_total_position(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Oreka.TotalNoOfData)
  return target;
}

::size_t TotalNoOfData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Oreka.TotalNoOfData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string type = 1;
  if (!this->_internal_type().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_type());
  }

  // uint32 TOTAL_DATA = 2;
  if (this->_internal_total_data() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_total_data());
  }

  // uint32 TOTAL_ORDER = 3;
  if (this->_internal_total_order() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_total_order());
  }

  // uint32 TOTAL_DEAL = 4;
  if (this->_internal_total_deal() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_total_deal());
  }

  // uint32 TOTAL_POSITION = 5;
  if (this->_internal_total_position() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_total_position());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TotalNoOfData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TotalNoOfData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TotalNoOfData::GetClassData() const { return &_class_data_; }


void TotalNoOfData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TotalNoOfData*>(&to_msg);
  auto& from = static_cast<const TotalNoOfData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Oreka.TotalNoOfData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_total_data() != 0) {
    _this->_internal_set_total_data(from._internal_total_data());
  }
  if (from._internal_total_order() != 0) {
    _this->_internal_set_total_order(from._internal_total_order());
  }
  if (from._internal_total_deal() != 0) {
    _this->_internal_set_total_deal(from._internal_total_deal());
  }
  if (from._internal_total_position() != 0) {
    _this->_internal_set_total_position(from._internal_total_position());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TotalNoOfData::CopyFrom(const TotalNoOfData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Oreka.TotalNoOfData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TotalNoOfData::IsInitialized() const {
  return true;
}

void TotalNoOfData::InternalSwap(TotalNoOfData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_, lhs_arena,
                                       &other->_impl_.type_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TotalNoOfData, _impl_.total_position_)
      + sizeof(TotalNoOfData::_impl_.total_position_)
      - PROTOBUF_FIELD_OFFSET(TotalNoOfData, _impl_.total_data_)>(
          reinterpret_cast<char*>(&_impl_.total_data_),
          reinterpret_cast<char*>(&other->_impl_.total_data_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TotalNoOfData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_TotalNoOfData_2eproto_getter, &descriptor_table_TotalNoOfData_2eproto_once,
      file_level_metadata_TotalNoOfData_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Oreka
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Oreka::TotalNoOfData*
Arena::CreateMaybeMessage< ::Oreka::TotalNoOfData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Oreka::TotalNoOfData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"

