// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "stdafx.h"

#include "UpdateRejectlimitSetting.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace Oreka {
template <typename>
PROTOBUF_CONSTEXPR UpdateRejectlimitSetting_Clientlimits::UpdateRejectlimitSetting_Clientlimits(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.login_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.symbolgroup_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.symbolwisebuylimit_)*/ 0u

  , /*decltype(_impl_.symbolwiseselllimit_)*/ 0u

  , /*decltype(_impl_.symbolwisependingorderenabledisable_)*/ false

  , /*decltype(_impl_.symbolpositionlimit_)*/ 0u

  , /*decltype(_impl_.qtylimitmultiplayer_)*/ 0u

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UpdateRejectlimitSetting_ClientlimitsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateRejectlimitSetting_ClientlimitsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateRejectlimitSetting_ClientlimitsDefaultTypeInternal() {}
  union {
    UpdateRejectlimitSetting_Clientlimits _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateRejectlimitSetting_ClientlimitsDefaultTypeInternal _UpdateRejectlimitSetting_Clientlimits_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR UpdateRejectlimitSetting::UpdateRejectlimitSetting(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.clientlimits_)*/{}
  , /*decltype(_impl_.type_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UpdateRejectlimitSettingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateRejectlimitSettingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateRejectlimitSettingDefaultTypeInternal() {}
  union {
    UpdateRejectlimitSetting _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateRejectlimitSettingDefaultTypeInternal _UpdateRejectlimitSetting_default_instance_;
}  // namespace Oreka
static ::_pb::Metadata file_level_metadata_UpdateRejectlimitSetting_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_UpdateRejectlimitSetting_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_UpdateRejectlimitSetting_2eproto = nullptr;
const ::uint32_t TableStruct_UpdateRejectlimitSetting_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Oreka::UpdateRejectlimitSetting_Clientlimits, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Oreka::UpdateRejectlimitSetting_Clientlimits, _impl_.login_),
    PROTOBUF_FIELD_OFFSET(::Oreka::UpdateRejectlimitSetting_Clientlimits, _impl_.symbolgroup_),
    PROTOBUF_FIELD_OFFSET(::Oreka::UpdateRejectlimitSetting_Clientlimits, _impl_.symbolwisebuylimit_),
    PROTOBUF_FIELD_OFFSET(::Oreka::UpdateRejectlimitSetting_Clientlimits, _impl_.symbolwiseselllimit_),
    PROTOBUF_FIELD_OFFSET(::Oreka::UpdateRejectlimitSetting_Clientlimits, _impl_.symbolwisependingorderenabledisable_),
    PROTOBUF_FIELD_OFFSET(::Oreka::UpdateRejectlimitSetting_Clientlimits, _impl_.symbolpositionlimit_),
    PROTOBUF_FIELD_OFFSET(::Oreka::UpdateRejectlimitSetting_Clientlimits, _impl_.qtylimitmultiplayer_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Oreka::UpdateRejectlimitSetting, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Oreka::UpdateRejectlimitSetting, _impl_.type_),
    PROTOBUF_FIELD_OFFSET(::Oreka::UpdateRejectlimitSetting, _impl_.clientlimits_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::Oreka::UpdateRejectlimitSetting_Clientlimits)},
        { 15, -1, -1, sizeof(::Oreka::UpdateRejectlimitSetting)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::Oreka::_UpdateRejectlimitSetting_Clientlimits_default_instance_._instance,
    &::Oreka::_UpdateRejectlimitSetting_default_instance_._instance,
};
const char descriptor_table_protodef_UpdateRejectlimitSetting_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\036UpdateRejectlimitSetting.proto\022\005Oreka\""
    "\301\002\n\030UpdateRejectlimitSetting\022\014\n\004type\030\001 \001"
    "(\t\022B\n\014clientlimits\030\002 \003(\0132,.Oreka.UpdateR"
    "ejectlimitSetting.Clientlimits\032\322\001\n\014Clien"
    "tlimits\022\r\n\005login\030\001 \001(\t\022\023\n\013symbolgroup\030\002 "
    "\001(\t\022\032\n\022symbolwisebuylimit\030\003 \001(\r\022\033\n\023symbo"
    "lwiseselllimit\030\004 \001(\r\022+\n#symbolwisependin"
    "gorderenabledisable\030\005 \001(\010\022\033\n\023symbolPosit"
    "ionLimit\030\006 \001(\r\022\033\n\023qtyLimitMultiplayer\030\007 "
    "\001(\rb\006proto3"
};
static ::absl::once_flag descriptor_table_UpdateRejectlimitSetting_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_UpdateRejectlimitSetting_2eproto = {
    false,
    false,
    371,
    descriptor_table_protodef_UpdateRejectlimitSetting_2eproto,
    "UpdateRejectlimitSetting.proto",
    &descriptor_table_UpdateRejectlimitSetting_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_UpdateRejectlimitSetting_2eproto::offsets,
    file_level_metadata_UpdateRejectlimitSetting_2eproto,
    file_level_enum_descriptors_UpdateRejectlimitSetting_2eproto,
    file_level_service_descriptors_UpdateRejectlimitSetting_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_UpdateRejectlimitSetting_2eproto_getter() {
  return &descriptor_table_UpdateRejectlimitSetting_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_UpdateRejectlimitSetting_2eproto(&descriptor_table_UpdateRejectlimitSetting_2eproto);
namespace Oreka {
// ===================================================================

class UpdateRejectlimitSetting_Clientlimits::_Internal {
 public:
};

UpdateRejectlimitSetting_Clientlimits::UpdateRejectlimitSetting_Clientlimits(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Oreka.UpdateRejectlimitSetting.Clientlimits)
}
UpdateRejectlimitSetting_Clientlimits::UpdateRejectlimitSetting_Clientlimits(const UpdateRejectlimitSetting_Clientlimits& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UpdateRejectlimitSetting_Clientlimits* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.login_) {}

    , decltype(_impl_.symbolgroup_) {}

    , decltype(_impl_.symbolwisebuylimit_) {}

    , decltype(_impl_.symbolwiseselllimit_) {}

    , decltype(_impl_.symbolwisependingorderenabledisable_) {}

    , decltype(_impl_.symbolpositionlimit_) {}

    , decltype(_impl_.qtylimitmultiplayer_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.login_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.login_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_login().empty()) {
    _this->_impl_.login_.Set(from._internal_login(), _this->GetArenaForAllocation());
  }
  _impl_.symbolgroup_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.symbolgroup_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_symbolgroup().empty()) {
    _this->_impl_.symbolgroup_.Set(from._internal_symbolgroup(), _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.symbolwisebuylimit_, &from._impl_.symbolwisebuylimit_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.qtylimitmultiplayer_) -
    reinterpret_cast<char*>(&_impl_.symbolwisebuylimit_)) + sizeof(_impl_.qtylimitmultiplayer_));
  // @@protoc_insertion_point(copy_constructor:Oreka.UpdateRejectlimitSetting.Clientlimits)
}

inline void UpdateRejectlimitSetting_Clientlimits::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.login_) {}

    , decltype(_impl_.symbolgroup_) {}

    , decltype(_impl_.symbolwisebuylimit_) { 0u }

    , decltype(_impl_.symbolwiseselllimit_) { 0u }

    , decltype(_impl_.symbolwisependingorderenabledisable_) { false }

    , decltype(_impl_.symbolpositionlimit_) { 0u }

    , decltype(_impl_.qtylimitmultiplayer_) { 0u }

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.login_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.login_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.symbolgroup_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.symbolgroup_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UpdateRejectlimitSetting_Clientlimits::~UpdateRejectlimitSetting_Clientlimits() {
  // @@protoc_insertion_point(destructor:Oreka.UpdateRejectlimitSetting.Clientlimits)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UpdateRejectlimitSetting_Clientlimits::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.login_.Destroy();
  _impl_.symbolgroup_.Destroy();
}

void UpdateRejectlimitSetting_Clientlimits::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UpdateRejectlimitSetting_Clientlimits::Clear() {
// @@protoc_insertion_point(message_clear_start:Oreka.UpdateRejectlimitSetting.Clientlimits)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.login_.ClearToEmpty();
  _impl_.symbolgroup_.ClearToEmpty();
  ::memset(&_impl_.symbolwisebuylimit_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.qtylimitmultiplayer_) -
      reinterpret_cast<char*>(&_impl_.symbolwisebuylimit_)) + sizeof(_impl_.qtylimitmultiplayer_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdateRejectlimitSetting_Clientlimits::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string login = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_login();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.UpdateRejectlimitSetting.Clientlimits.login"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string symbolgroup = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_symbolgroup();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.UpdateRejectlimitSetting.Clientlimits.symbolgroup"));
        } else {
          goto handle_unusual;
        }
        continue;
      // uint32 symbolwisebuylimit = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 24)) {
          _impl_.symbolwisebuylimit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // uint32 symbolwiseselllimit = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 32)) {
          _impl_.symbolwiseselllimit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // bool symbolwisependingorderenabledisable = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 40)) {
          _impl_.symbolwisependingorderenabledisable_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // uint32 symbolPositionLimit = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 48)) {
          _impl_.symbolpositionlimit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // uint32 qtyLimitMultiplayer = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 56)) {
          _impl_.qtylimitmultiplayer_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* UpdateRejectlimitSetting_Clientlimits::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Oreka.UpdateRejectlimitSetting.Clientlimits)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string login = 1;
  if (!this->_internal_login().empty()) {
    const std::string& _s = this->_internal_login();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.UpdateRejectlimitSetting.Clientlimits.login");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string symbolgroup = 2;
  if (!this->_internal_symbolgroup().empty()) {
    const std::string& _s = this->_internal_symbolgroup();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.UpdateRejectlimitSetting.Clientlimits.symbolgroup");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // uint32 symbolwisebuylimit = 3;
  if (this->_internal_symbolwisebuylimit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_symbolwisebuylimit(), target);
  }

  // uint32 symbolwiseselllimit = 4;
  if (this->_internal_symbolwiseselllimit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_symbolwiseselllimit(), target);
  }

  // bool symbolwisependingorderenabledisable = 5;
  if (this->_internal_symbolwisependingorderenabledisable() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        5, this->_internal_symbolwisependingorderenabledisable(), target);
  }

  // uint32 symbolPositionLimit = 6;
  if (this->_internal_symbolpositionlimit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this->_internal_symbolpositionlimit(), target);
  }

  // uint32 qtyLimitMultiplayer = 7;
  if (this->_internal_qtylimitmultiplayer() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        7, this->_internal_qtylimitmultiplayer(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Oreka.UpdateRejectlimitSetting.Clientlimits)
  return target;
}

::size_t UpdateRejectlimitSetting_Clientlimits::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Oreka.UpdateRejectlimitSetting.Clientlimits)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string login = 1;
  if (!this->_internal_login().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_login());
  }

  // string symbolgroup = 2;
  if (!this->_internal_symbolgroup().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_symbolgroup());
  }

  // uint32 symbolwisebuylimit = 3;
  if (this->_internal_symbolwisebuylimit() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_symbolwisebuylimit());
  }

  // uint32 symbolwiseselllimit = 4;
  if (this->_internal_symbolwiseselllimit() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_symbolwiseselllimit());
  }

  // bool symbolwisependingorderenabledisable = 5;
  if (this->_internal_symbolwisependingorderenabledisable() != 0) {
    total_size += 2;
  }

  // uint32 symbolPositionLimit = 6;
  if (this->_internal_symbolpositionlimit() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_symbolpositionlimit());
  }

  // uint32 qtyLimitMultiplayer = 7;
  if (this->_internal_qtylimitmultiplayer() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_qtylimitmultiplayer());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpdateRejectlimitSetting_Clientlimits::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UpdateRejectlimitSetting_Clientlimits::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpdateRejectlimitSetting_Clientlimits::GetClassData() const { return &_class_data_; }


void UpdateRejectlimitSetting_Clientlimits::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UpdateRejectlimitSetting_Clientlimits*>(&to_msg);
  auto& from = static_cast<const UpdateRejectlimitSetting_Clientlimits&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Oreka.UpdateRejectlimitSetting.Clientlimits)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_login().empty()) {
    _this->_internal_set_login(from._internal_login());
  }
  if (!from._internal_symbolgroup().empty()) {
    _this->_internal_set_symbolgroup(from._internal_symbolgroup());
  }
  if (from._internal_symbolwisebuylimit() != 0) {
    _this->_internal_set_symbolwisebuylimit(from._internal_symbolwisebuylimit());
  }
  if (from._internal_symbolwiseselllimit() != 0) {
    _this->_internal_set_symbolwiseselllimit(from._internal_symbolwiseselllimit());
  }
  if (from._internal_symbolwisependingorderenabledisable() != 0) {
    _this->_internal_set_symbolwisependingorderenabledisable(from._internal_symbolwisependingorderenabledisable());
  }
  if (from._internal_symbolpositionlimit() != 0) {
    _this->_internal_set_symbolpositionlimit(from._internal_symbolpositionlimit());
  }
  if (from._internal_qtylimitmultiplayer() != 0) {
    _this->_internal_set_qtylimitmultiplayer(from._internal_qtylimitmultiplayer());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateRejectlimitSetting_Clientlimits::CopyFrom(const UpdateRejectlimitSetting_Clientlimits& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Oreka.UpdateRejectlimitSetting.Clientlimits)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateRejectlimitSetting_Clientlimits::IsInitialized() const {
  return true;
}

void UpdateRejectlimitSetting_Clientlimits::InternalSwap(UpdateRejectlimitSetting_Clientlimits* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.login_, lhs_arena,
                                       &other->_impl_.login_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.symbolgroup_, lhs_arena,
                                       &other->_impl_.symbolgroup_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateRejectlimitSetting_Clientlimits, _impl_.qtylimitmultiplayer_)
      + sizeof(UpdateRejectlimitSetting_Clientlimits::_impl_.qtylimitmultiplayer_)
      - PROTOBUF_FIELD_OFFSET(UpdateRejectlimitSetting_Clientlimits, _impl_.symbolwisebuylimit_)>(
          reinterpret_cast<char*>(&_impl_.symbolwisebuylimit_),
          reinterpret_cast<char*>(&other->_impl_.symbolwisebuylimit_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdateRejectlimitSetting_Clientlimits::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_UpdateRejectlimitSetting_2eproto_getter, &descriptor_table_UpdateRejectlimitSetting_2eproto_once,
      file_level_metadata_UpdateRejectlimitSetting_2eproto[0]);
}
// ===================================================================

class UpdateRejectlimitSetting::_Internal {
 public:
};

UpdateRejectlimitSetting::UpdateRejectlimitSetting(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Oreka.UpdateRejectlimitSetting)
}
UpdateRejectlimitSetting::UpdateRejectlimitSetting(const UpdateRejectlimitSetting& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UpdateRejectlimitSetting* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.clientlimits_){from._impl_.clientlimits_}
    , decltype(_impl_.type_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_type().empty()) {
    _this->_impl_.type_.Set(from._internal_type(), _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:Oreka.UpdateRejectlimitSetting)
}

inline void UpdateRejectlimitSetting::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.clientlimits_){arena}
    , decltype(_impl_.type_) {}

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UpdateRejectlimitSetting::~UpdateRejectlimitSetting() {
  // @@protoc_insertion_point(destructor:Oreka.UpdateRejectlimitSetting)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UpdateRejectlimitSetting::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _internal_mutable_clientlimits()->~RepeatedPtrField();
  _impl_.type_.Destroy();
}

void UpdateRejectlimitSetting::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UpdateRejectlimitSetting::Clear() {
// @@protoc_insertion_point(message_clear_start:Oreka.UpdateRejectlimitSetting)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_clientlimits()->Clear();
  _impl_.type_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdateRejectlimitSetting::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Oreka.UpdateRejectlimitSetting.type"));
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated .Oreka.UpdateRejectlimitSetting.Clientlimits clientlimits = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_clientlimits(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* UpdateRejectlimitSetting::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Oreka.UpdateRejectlimitSetting)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (!this->_internal_type().empty()) {
    const std::string& _s = this->_internal_type();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Oreka.UpdateRejectlimitSetting.type");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated .Oreka.UpdateRejectlimitSetting.Clientlimits clientlimits = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_clientlimits_size()); i < n; i++) {
    const auto& repfield = this->_internal_clientlimits(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Oreka.UpdateRejectlimitSetting)
  return target;
}

::size_t UpdateRejectlimitSetting::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Oreka.UpdateRejectlimitSetting)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Oreka.UpdateRejectlimitSetting.Clientlimits clientlimits = 2;
  total_size += 1UL * this->_internal_clientlimits_size();
  for (const auto& msg : this->_internal_clientlimits()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string type = 1;
  if (!this->_internal_type().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpdateRejectlimitSetting::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UpdateRejectlimitSetting::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpdateRejectlimitSetting::GetClassData() const { return &_class_data_; }


void UpdateRejectlimitSetting::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UpdateRejectlimitSetting*>(&to_msg);
  auto& from = static_cast<const UpdateRejectlimitSetting&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Oreka.UpdateRejectlimitSetting)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_clientlimits()->MergeFrom(from._internal_clientlimits());
  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateRejectlimitSetting::CopyFrom(const UpdateRejectlimitSetting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Oreka.UpdateRejectlimitSetting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateRejectlimitSetting::IsInitialized() const {
  return true;
}

void UpdateRejectlimitSetting::InternalSwap(UpdateRejectlimitSetting* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _internal_mutable_clientlimits()->InternalSwap(other->_internal_mutable_clientlimits());
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_, lhs_arena,
                                       &other->_impl_.type_, rhs_arena);
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdateRejectlimitSetting::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_UpdateRejectlimitSetting_2eproto_getter, &descriptor_table_UpdateRejectlimitSetting_2eproto_once,
      file_level_metadata_UpdateRejectlimitSetting_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Oreka
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Oreka::UpdateRejectlimitSetting_Clientlimits*
Arena::CreateMaybeMessage< ::Oreka::UpdateRejectlimitSetting_Clientlimits >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Oreka::UpdateRejectlimitSetting_Clientlimits >(arena);
}
template<> PROTOBUF_NOINLINE ::Oreka::UpdateRejectlimitSetting*
Arena::CreateMaybeMessage< ::Oreka::UpdateRejectlimitSetting >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Oreka::UpdateRejectlimitSetting >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"

