// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateClientcredit.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_UpdateClientcredit_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_UpdateClientcredit_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_UpdateClientcredit_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_UpdateClientcredit_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_UpdateClientcredit_2eproto;
namespace Oreka {
class UpdateClientcredit;
struct UpdateClientcreditDefaultTypeInternal;
extern UpdateClientcreditDefaultTypeInternal _UpdateClientcredit_default_instance_;
class UpdateClientcredit_Clientcredits;
struct UpdateClientcredit_ClientcreditsDefaultTypeInternal;
extern UpdateClientcredit_ClientcreditsDefaultTypeInternal _UpdateClientcredit_Clientcredits_default_instance_;
}  // namespace Oreka
PROTOBUF_NAMESPACE_OPEN
template <>
::Oreka::UpdateClientcredit* Arena::CreateMaybeMessage<::Oreka::UpdateClientcredit>(Arena*);
template <>
::Oreka::UpdateClientcredit_Clientcredits* Arena::CreateMaybeMessage<::Oreka::UpdateClientcredit_Clientcredits>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace Oreka {

// ===================================================================


// -------------------------------------------------------------------

class UpdateClientcredit_Clientcredits final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Oreka.UpdateClientcredit.Clientcredits) */ {
 public:
  inline UpdateClientcredit_Clientcredits() : UpdateClientcredit_Clientcredits(nullptr) {}
  ~UpdateClientcredit_Clientcredits() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR UpdateClientcredit_Clientcredits(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UpdateClientcredit_Clientcredits(const UpdateClientcredit_Clientcredits& from);
  UpdateClientcredit_Clientcredits(UpdateClientcredit_Clientcredits&& from) noexcept
    : UpdateClientcredit_Clientcredits() {
    *this = ::std::move(from);
  }

  inline UpdateClientcredit_Clientcredits& operator=(const UpdateClientcredit_Clientcredits& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateClientcredit_Clientcredits& operator=(UpdateClientcredit_Clientcredits&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpdateClientcredit_Clientcredits& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpdateClientcredit_Clientcredits* internal_default_instance() {
    return reinterpret_cast<const UpdateClientcredit_Clientcredits*>(
               &_UpdateClientcredit_Clientcredits_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UpdateClientcredit_Clientcredits& a, UpdateClientcredit_Clientcredits& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateClientcredit_Clientcredits* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateClientcredit_Clientcredits* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateClientcredit_Clientcredits* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UpdateClientcredit_Clientcredits>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UpdateClientcredit_Clientcredits& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UpdateClientcredit_Clientcredits& from) {
    UpdateClientcredit_Clientcredits::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateClientcredit_Clientcredits* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Oreka.UpdateClientcredit.Clientcredits";
  }
  protected:
  explicit UpdateClientcredit_Clientcredits(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLoginFieldNumber = 1,
    kCreditFieldNumber = 2,
  };
  // string login = 1;
  void clear_login() ;
  const std::string& login() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_login(Arg_&& arg, Args_... args);
  std::string* mutable_login();
  PROTOBUF_NODISCARD std::string* release_login();
  void set_allocated_login(std::string* ptr);

  private:
  const std::string& _internal_login() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_login(
      const std::string& value);
  std::string* _internal_mutable_login();

  public:
  // double credit = 2;
  void clear_credit() ;
  double credit() const;
  void set_credit(double value);

  private:
  double _internal_credit() const;
  void _internal_set_credit(double value);

  public:
  // @@protoc_insertion_point(class_scope:Oreka.UpdateClientcredit.Clientcredits)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr login_;
    double credit_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_UpdateClientcredit_2eproto;
};// -------------------------------------------------------------------

class UpdateClientcredit final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Oreka.UpdateClientcredit) */ {
 public:
  inline UpdateClientcredit() : UpdateClientcredit(nullptr) {}
  ~UpdateClientcredit() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR UpdateClientcredit(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UpdateClientcredit(const UpdateClientcredit& from);
  UpdateClientcredit(UpdateClientcredit&& from) noexcept
    : UpdateClientcredit() {
    *this = ::std::move(from);
  }

  inline UpdateClientcredit& operator=(const UpdateClientcredit& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateClientcredit& operator=(UpdateClientcredit&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpdateClientcredit& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpdateClientcredit* internal_default_instance() {
    return reinterpret_cast<const UpdateClientcredit*>(
               &_UpdateClientcredit_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UpdateClientcredit& a, UpdateClientcredit& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateClientcredit* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateClientcredit* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateClientcredit* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UpdateClientcredit>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UpdateClientcredit& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UpdateClientcredit& from) {
    UpdateClientcredit::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateClientcredit* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Oreka.UpdateClientcredit";
  }
  protected:
  explicit UpdateClientcredit(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef UpdateClientcredit_Clientcredits Clientcredits;

  // accessors -------------------------------------------------------

  enum : int {
    kClientcreditsFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // repeated .Oreka.UpdateClientcredit.Clientcredits clientcredits = 2;
  int clientcredits_size() const;
  private:
  int _internal_clientcredits_size() const;

  public:
  void clear_clientcredits() ;
  ::Oreka::UpdateClientcredit_Clientcredits* mutable_clientcredits(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::UpdateClientcredit_Clientcredits >*
      mutable_clientcredits();
  private:
  const ::Oreka::UpdateClientcredit_Clientcredits& _internal_clientcredits(int index) const;
  ::Oreka::UpdateClientcredit_Clientcredits* _internal_add_clientcredits();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::UpdateClientcredit_Clientcredits>& _internal_clientcredits() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::UpdateClientcredit_Clientcredits>* _internal_mutable_clientcredits();
  public:
  const ::Oreka::UpdateClientcredit_Clientcredits& clientcredits(int index) const;
  ::Oreka::UpdateClientcredit_Clientcredits* add_clientcredits();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::UpdateClientcredit_Clientcredits >&
      clientcredits() const;
  // string type = 1;
  void clear_type() ;
  const std::string& type() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* ptr);

  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(
      const std::string& value);
  std::string* _internal_mutable_type();

  public:
  // @@protoc_insertion_point(class_scope:Oreka.UpdateClientcredit)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::UpdateClientcredit_Clientcredits > clientcredits_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_UpdateClientcredit_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// UpdateClientcredit_Clientcredits

// string login = 1;
inline void UpdateClientcredit_Clientcredits::clear_login() {
  _impl_.login_.ClearToEmpty();
}
inline const std::string& UpdateClientcredit_Clientcredits::login() const {
  // @@protoc_insertion_point(field_get:Oreka.UpdateClientcredit.Clientcredits.login)
  return _internal_login();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UpdateClientcredit_Clientcredits::set_login(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.login_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.UpdateClientcredit.Clientcredits.login)
}
inline std::string* UpdateClientcredit_Clientcredits::mutable_login() {
  std::string* _s = _internal_mutable_login();
  // @@protoc_insertion_point(field_mutable:Oreka.UpdateClientcredit.Clientcredits.login)
  return _s;
}
inline const std::string& UpdateClientcredit_Clientcredits::_internal_login() const {
  return _impl_.login_.Get();
}
inline void UpdateClientcredit_Clientcredits::_internal_set_login(const std::string& value) {
  ;


  _impl_.login_.Set(value, GetArenaForAllocation());
}
inline std::string* UpdateClientcredit_Clientcredits::_internal_mutable_login() {
  ;
  return _impl_.login_.Mutable( GetArenaForAllocation());
}
inline std::string* UpdateClientcredit_Clientcredits::release_login() {
  // @@protoc_insertion_point(field_release:Oreka.UpdateClientcredit.Clientcredits.login)
  return _impl_.login_.Release();
}
inline void UpdateClientcredit_Clientcredits::set_allocated_login(std::string* value) {
  _impl_.login_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.login_.IsDefault()) {
          _impl_.login_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.UpdateClientcredit.Clientcredits.login)
}

// double credit = 2;
inline void UpdateClientcredit_Clientcredits::clear_credit() {
  _impl_.credit_ = 0;
}
inline double UpdateClientcredit_Clientcredits::credit() const {
  // @@protoc_insertion_point(field_get:Oreka.UpdateClientcredit.Clientcredits.credit)
  return _internal_credit();
}
inline void UpdateClientcredit_Clientcredits::set_credit(double value) {
  _internal_set_credit(value);
  // @@protoc_insertion_point(field_set:Oreka.UpdateClientcredit.Clientcredits.credit)
}
inline double UpdateClientcredit_Clientcredits::_internal_credit() const {
  return _impl_.credit_;
}
inline void UpdateClientcredit_Clientcredits::_internal_set_credit(double value) {
  ;
  _impl_.credit_ = value;
}

// -------------------------------------------------------------------

// UpdateClientcredit

// string type = 1;
inline void UpdateClientcredit::clear_type() {
  _impl_.type_.ClearToEmpty();
}
inline const std::string& UpdateClientcredit::type() const {
  // @@protoc_insertion_point(field_get:Oreka.UpdateClientcredit.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UpdateClientcredit::set_type(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Oreka.UpdateClientcredit.type)
}
inline std::string* UpdateClientcredit::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:Oreka.UpdateClientcredit.type)
  return _s;
}
inline const std::string& UpdateClientcredit::_internal_type() const {
  return _impl_.type_.Get();
}
inline void UpdateClientcredit::_internal_set_type(const std::string& value) {
  ;


  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* UpdateClientcredit::_internal_mutable_type() {
  ;
  return _impl_.type_.Mutable( GetArenaForAllocation());
}
inline std::string* UpdateClientcredit::release_type() {
  // @@protoc_insertion_point(field_release:Oreka.UpdateClientcredit.type)
  return _impl_.type_.Release();
}
inline void UpdateClientcredit::set_allocated_type(std::string* value) {
  _impl_.type_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.type_.IsDefault()) {
          _impl_.type_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Oreka.UpdateClientcredit.type)
}

// repeated .Oreka.UpdateClientcredit.Clientcredits clientcredits = 2;
inline int UpdateClientcredit::_internal_clientcredits_size() const {
  return _impl_.clientcredits_.size();
}
inline int UpdateClientcredit::clientcredits_size() const {
  return _internal_clientcredits_size();
}
inline void UpdateClientcredit::clear_clientcredits() {
  _internal_mutable_clientcredits()->Clear();
}
inline ::Oreka::UpdateClientcredit_Clientcredits* UpdateClientcredit::mutable_clientcredits(int index) {
  // @@protoc_insertion_point(field_mutable:Oreka.UpdateClientcredit.clientcredits)
  return _internal_mutable_clientcredits()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::UpdateClientcredit_Clientcredits >*
UpdateClientcredit::mutable_clientcredits() {
  // @@protoc_insertion_point(field_mutable_list:Oreka.UpdateClientcredit.clientcredits)
  return _internal_mutable_clientcredits();
}
inline const ::Oreka::UpdateClientcredit_Clientcredits& UpdateClientcredit::_internal_clientcredits(int index) const {
  return _internal_clientcredits().Get(index);
}
inline const ::Oreka::UpdateClientcredit_Clientcredits& UpdateClientcredit::clientcredits(int index) const {
  // @@protoc_insertion_point(field_get:Oreka.UpdateClientcredit.clientcredits)
  return _internal_clientcredits(index);
}
inline ::Oreka::UpdateClientcredit_Clientcredits* UpdateClientcredit::_internal_add_clientcredits() {
  return _internal_mutable_clientcredits()->Add();
}
inline ::Oreka::UpdateClientcredit_Clientcredits* UpdateClientcredit::add_clientcredits() {
  ::Oreka::UpdateClientcredit_Clientcredits* _add = _internal_add_clientcredits();
  // @@protoc_insertion_point(field_add:Oreka.UpdateClientcredit.clientcredits)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Oreka::UpdateClientcredit_Clientcredits >&
UpdateClientcredit::clientcredits() const {
  // @@protoc_insertion_point(field_list:Oreka.UpdateClientcredit.clientcredits)
  return _internal_clientcredits();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::UpdateClientcredit_Clientcredits>&
UpdateClientcredit::_internal_clientcredits() const {
  return _impl_.clientcredits_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::Oreka::UpdateClientcredit_Clientcredits>*
UpdateClientcredit::_internal_mutable_clientcredits() {
  return &_impl_.clientcredits_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Oreka


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_UpdateClientcredit_2eproto_2epb_2eh
