// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_authorization_2.proto
#include "StdAfx.h"
#include "account_authorization_2.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace account_authorization_2 {
template <typename>
PROTOBUF_CONSTEXPR AccountLogon::AccountLogon(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.username_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.password_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.account_id_)*/ 0
} {}
struct AccountLogonDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AccountLogonDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AccountLogonDefaultTypeInternal() {}
  union {
    AccountLogon _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AccountLogonDefaultTypeInternal _AccountLogon_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR AccountLogonResult::AccountLogonResult(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.text_message_)*/nullptr
  , /*decltype(_impl_.server_utc_timestamp_)*/nullptr
  , /*decltype(_impl_.account_id_)*/ 0

  , /*decltype(_impl_.result_code_)*/ 0u
} {}
struct AccountLogonResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AccountLogonResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AccountLogonResultDefaultTypeInternal() {}
  union {
    AccountLogonResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AccountLogonResultDefaultTypeInternal _AccountLogonResult_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR AccountPasswordChange::AccountPasswordChange(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.old_password_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.new_password_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.account_id_)*/ 0
} {}
struct AccountPasswordChangeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AccountPasswordChangeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AccountPasswordChangeDefaultTypeInternal() {}
  union {
    AccountPasswordChange _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AccountPasswordChangeDefaultTypeInternal _AccountPasswordChange_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR AccountPasswordChangeResult::AccountPasswordChangeResult(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.text_message_)*/nullptr
  , /*decltype(_impl_.account_id_)*/ 0

  , /*decltype(_impl_.result_code_)*/ 0u
} {}
struct AccountPasswordChangeResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AccountPasswordChangeResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AccountPasswordChangeResultDefaultTypeInternal() {}
  union {
    AccountPasswordChangeResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AccountPasswordChangeResultDefaultTypeInternal _AccountPasswordChangeResult_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR AccountLogoff::AccountLogoff(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.account_id_)*/ 0
} {}
struct AccountLogoffDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AccountLogoffDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AccountLogoffDefaultTypeInternal() {}
  union {
    AccountLogoff _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AccountLogoffDefaultTypeInternal _AccountLogoff_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR AccountLogoffResult::AccountLogoffResult(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.text_message_)*/nullptr
  , /*decltype(_impl_.server_utc_timestamp_)*/nullptr
  , /*decltype(_impl_.account_id_)*/ 0

  , /*decltype(_impl_.result_code_)*/ 0u
} {}
struct AccountLogoffResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AccountLogoffResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AccountLogoffResultDefaultTypeInternal() {}
  union {
    AccountLogoffResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AccountLogoffResultDefaultTypeInternal _AccountLogoffResult_default_instance_;
}  // namespace account_authorization_2
static ::_pb::Metadata file_level_metadata_account_5fauthorization_5f2_2eproto[6];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_account_5fauthorization_5f2_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_account_5fauthorization_5f2_2eproto = nullptr;
const ::uint32_t TableStruct_account_5fauthorization_5f2_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogon, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogon, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogon, _impl_.account_id_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogon, _impl_.username_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogon, _impl_.password_),
    2,
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogonResult, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogonResult, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogonResult, _impl_.account_id_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogonResult, _impl_.result_code_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogonResult, _impl_.text_message_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogonResult, _impl_.server_utc_timestamp_),
    2,
    3,
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountPasswordChange, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountPasswordChange, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountPasswordChange, _impl_.account_id_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountPasswordChange, _impl_.old_password_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountPasswordChange, _impl_.new_password_),
    2,
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountPasswordChangeResult, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountPasswordChangeResult, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountPasswordChangeResult, _impl_.account_id_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountPasswordChangeResult, _impl_.result_code_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountPasswordChangeResult, _impl_.text_message_),
    1,
    2,
    0,
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogoff, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogoff, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogoff, _impl_.account_id_),
    0,
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogoffResult, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogoffResult, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogoffResult, _impl_.account_id_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogoffResult, _impl_.result_code_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogoffResult, _impl_.text_message_),
    PROTOBUF_FIELD_OFFSET(::account_authorization_2::AccountLogoffResult, _impl_.server_utc_timestamp_),
    2,
    3,
    0,
    1,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 11, -1, sizeof(::account_authorization_2::AccountLogon)},
        { 14, 26, -1, sizeof(::account_authorization_2::AccountLogonResult)},
        { 30, 41, -1, sizeof(::account_authorization_2::AccountPasswordChange)},
        { 44, 55, -1, sizeof(::account_authorization_2::AccountPasswordChangeResult)},
        { 58, 67, -1, sizeof(::account_authorization_2::AccountLogoff)},
        { 68, 80, -1, sizeof(::account_authorization_2::AccountLogoffResult)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::account_authorization_2::_AccountLogon_default_instance_._instance,
    &::account_authorization_2::_AccountLogonResult_default_instance_._instance,
    &::account_authorization_2::_AccountPasswordChange_default_instance_._instance,
    &::account_authorization_2::_AccountPasswordChangeResult_default_instance_._instance,
    &::account_authorization_2::_AccountLogoff_default_instance_._instance,
    &::account_authorization_2::_AccountLogoffResult_default_instance_._instance,
};
const char descriptor_table_protodef_account_5fauthorization_5f2_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\035account_authorization_2.proto\022\027account"
    "_authorization_2\032\025common/shared_1.proto\032"
    "\037google/protobuf/timestamp.proto\"F\n\014Acco"
    "untLogon\022\022\n\naccount_id\030\001 \002(\021\022\020\n\010username"
    "\030\002 \002(\t\022\020\n\010password\030\003 \002(\t\"\252\002\n\022AccountLogo"
    "nResult\022\022\n\naccount_id\030\001 \002(\021\022\023\n\013result_co"
    "de\030\002 \002(\r\022$\n\014text_message\030\003 \001(\0132\016.shared_"
    "1.Text\0228\n\024server_utc_timestamp\030\004 \002(\0132\032.g"
    "oogle.protobuf.Timestamp\"\212\001\n\nResultCode\022"
    "\027\n\023RESULT_CODE_SUCCESS\020\000\022(\n$RESULT_CODE_"
    "PASSWORD_CHANGE_REQUIRED\020\001\022 \n\034RESULT_COD"
    "E_PASSWORD_EXPIRED\020\002\022\027\n\023RESULT_CODE_FAIL"
    "URE\020e\"W\n\025AccountPasswordChange\022\022\n\naccoun"
    "t_id\030\001 \002(\021\022\024\n\014old_password\030\002 \002(\t\022\024\n\014new_"
    "password\030\003 \002(\t\"\254\001\n\033AccountPasswordChange"
    "Result\022\022\n\naccount_id\030\001 \002(\021\022\023\n\013result_cod"
    "e\030\002 \002(\r\022$\n\014text_message\030\003 \001(\0132\016.shared_1"
    ".Text\">\n\nResultCode\022\027\n\023RESULT_CODE_SUCCE"
    "SS\020\000\022\027\n\023RESULT_CODE_FAILURE\020e\"#\n\rAccount"
    "Logoff\022\022\n\naccount_id\030\001 \002(\021\"\336\001\n\023AccountLo"
    "goffResult\022\022\n\naccount_id\030\001 \002(\021\022\023\n\013result"
    "_code\030\002 \002(\r\022$\n\014text_message\030\003 \001(\0132\016.shar"
    "ed_1.Text\0228\n\024server_utc_timestamp\030\004 \002(\0132"
    "\032.google.protobuf.Timestamp\">\n\nResultCod"
    "e\022\027\n\023RESULT_CODE_SUCCESS\020\000\022\027\n\023RESULT_COD"
    "E_FAILURE\020e"
};
static const ::_pbi::DescriptorTable* const descriptor_table_account_5fauthorization_5f2_2eproto_deps[2] =
    {
        &::descriptor_table_common_2fshared_5f1_2eproto,
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_account_5fauthorization_5f2_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_account_5fauthorization_5f2_2eproto = {
    false,
    false,
    1011,
    descriptor_table_protodef_account_5fauthorization_5f2_2eproto,
    "account_authorization_2.proto",
    &descriptor_table_account_5fauthorization_5f2_2eproto_once,
    descriptor_table_account_5fauthorization_5f2_2eproto_deps,
    2,
    6,
    schemas,
    file_default_instances,
    TableStruct_account_5fauthorization_5f2_2eproto::offsets,
    file_level_metadata_account_5fauthorization_5f2_2eproto,
    file_level_enum_descriptors_account_5fauthorization_5f2_2eproto,
    file_level_service_descriptors_account_5fauthorization_5f2_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_account_5fauthorization_5f2_2eproto_getter() {
  return &descriptor_table_account_5fauthorization_5f2_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_account_5fauthorization_5f2_2eproto(&descriptor_table_account_5fauthorization_5f2_2eproto);
namespace account_authorization_2 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AccountLogonResult_ResultCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_account_5fauthorization_5f2_2eproto);
  return file_level_enum_descriptors_account_5fauthorization_5f2_2eproto[0];
}
bool AccountLogonResult_ResultCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 101:
      return true;
    default:
      return false;
  }
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr AccountLogonResult_ResultCode AccountLogonResult::RESULT_CODE_SUCCESS;
constexpr AccountLogonResult_ResultCode AccountLogonResult::RESULT_CODE_PASSWORD_CHANGE_REQUIRED;
constexpr AccountLogonResult_ResultCode AccountLogonResult::RESULT_CODE_PASSWORD_EXPIRED;
constexpr AccountLogonResult_ResultCode AccountLogonResult::RESULT_CODE_FAILURE;
constexpr AccountLogonResult_ResultCode AccountLogonResult::ResultCode_MIN;
constexpr AccountLogonResult_ResultCode AccountLogonResult::ResultCode_MAX;
constexpr int AccountLogonResult::ResultCode_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AccountPasswordChangeResult_ResultCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_account_5fauthorization_5f2_2eproto);
  return file_level_enum_descriptors_account_5fauthorization_5f2_2eproto[1];
}
bool AccountPasswordChangeResult_ResultCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 101:
      return true;
    default:
      return false;
  }
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr AccountPasswordChangeResult_ResultCode AccountPasswordChangeResult::RESULT_CODE_SUCCESS;
constexpr AccountPasswordChangeResult_ResultCode AccountPasswordChangeResult::RESULT_CODE_FAILURE;
constexpr AccountPasswordChangeResult_ResultCode AccountPasswordChangeResult::ResultCode_MIN;
constexpr AccountPasswordChangeResult_ResultCode AccountPasswordChangeResult::ResultCode_MAX;
constexpr int AccountPasswordChangeResult::ResultCode_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AccountLogoffResult_ResultCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_account_5fauthorization_5f2_2eproto);
  return file_level_enum_descriptors_account_5fauthorization_5f2_2eproto[2];
}
bool AccountLogoffResult_ResultCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 101:
      return true;
    default:
      return false;
  }
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr AccountLogoffResult_ResultCode AccountLogoffResult::RESULT_CODE_SUCCESS;
constexpr AccountLogoffResult_ResultCode AccountLogoffResult::RESULT_CODE_FAILURE;
constexpr AccountLogoffResult_ResultCode AccountLogoffResult::ResultCode_MIN;
constexpr AccountLogoffResult_ResultCode AccountLogoffResult::ResultCode_MAX;
constexpr int AccountLogoffResult::ResultCode_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class AccountLogon::_Internal {
 public:
  using HasBits = decltype(std::declval<AccountLogon>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AccountLogon, _impl_._has_bits_);
  static void set_has_account_id(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_username(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_password(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

AccountLogon::AccountLogon(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:account_authorization_2.AccountLogon)
}
AccountLogon::AccountLogon(const AccountLogon& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AccountLogon* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.username_) {}

    , decltype(_impl_.password_) {}

    , decltype(_impl_.account_id_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.username_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.username_.Set(from._internal_username(), _this->GetArenaForAllocation());
  }
  _impl_.password_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.password_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.password_.Set(from._internal_password(), _this->GetArenaForAllocation());
  }
  _this->_impl_.account_id_ = from._impl_.account_id_;
  // @@protoc_insertion_point(copy_constructor:account_authorization_2.AccountLogon)
}

inline void AccountLogon::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.username_) {}

    , decltype(_impl_.password_) {}

    , decltype(_impl_.account_id_) { 0 }

  };
  _impl_.username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.username_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.password_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.password_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AccountLogon::~AccountLogon() {
  // @@protoc_insertion_point(destructor:account_authorization_2.AccountLogon)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AccountLogon::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.username_.Destroy();
  _impl_.password_.Destroy();
}

void AccountLogon::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AccountLogon::Clear() {
// @@protoc_insertion_point(message_clear_start:account_authorization_2.AccountLogon)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.username_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.password_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.account_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AccountLogon::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required sint32 account_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_account_id(&has_bits);
          _impl_.account_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // required string username = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_username();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "account_authorization_2.AccountLogon.username");
          #endif  // !NDEBUG
        } else {
          goto handle_unusual;
        }
        continue;
      // required string password = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_password();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "account_authorization_2.AccountLogon.password");
          #endif  // !NDEBUG
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* AccountLogon::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:account_authorization_2.AccountLogon)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required sint32 account_id = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
        1, this->_internal_account_id(), target);
  }

  // required string username = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_username();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
                                "account_authorization_2.AccountLogon.username");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // required string password = 3;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_password();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
                                "account_authorization_2.AccountLogon.password");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:account_authorization_2.AccountLogon)
  return target;
}

::size_t AccountLogon::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:account_authorization_2.AccountLogon)
  ::size_t total_size = 0;

  if ((_impl_._has_bits_[0] & 0x00000001u) != 0) {
    // required string username = 2;
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_username());
  }

  if ((_impl_._has_bits_[0] & 0x00000002u) != 0) {
    // required string password = 3;
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_password());
  }

  if ((_impl_._has_bits_[0] & 0x00000004u) != 0) {
    // required sint32 account_id = 1;
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
        this->_internal_account_id());
  }

  return total_size;
}
::size_t AccountLogon::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:account_authorization_2.AccountLogon)
  ::size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string username = 2;
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_username());

    // required string password = 3;
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_password());

    // required sint32 account_id = 1;
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
        this->_internal_account_id());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AccountLogon::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AccountLogon::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AccountLogon::GetClassData() const { return &_class_data_; }


void AccountLogon::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AccountLogon*>(&to_msg);
  auto& from = static_cast<const AccountLogon&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:account_authorization_2.AccountLogon)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_username(from._internal_username());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_password(from._internal_password());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.account_id_ = from._impl_.account_id_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AccountLogon::CopyFrom(const AccountLogon& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:account_authorization_2.AccountLogon)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AccountLogon::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void AccountLogon::InternalSwap(AccountLogon* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, lhs_arena,
                                       &other->_impl_.username_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, lhs_arena,
                                       &other->_impl_.password_, rhs_arena);

  swap(_impl_.account_id_, other->_impl_.account_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AccountLogon::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_account_5fauthorization_5f2_2eproto_getter, &descriptor_table_account_5fauthorization_5f2_2eproto_once,
      file_level_metadata_account_5fauthorization_5f2_2eproto[0]);
}
// ===================================================================

class AccountLogonResult::_Internal {
 public:
  using HasBits = decltype(std::declval<AccountLogonResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AccountLogonResult, _impl_._has_bits_);
  static void set_has_account_id(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_result_code(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static const ::shared_1::Text& text_message(const AccountLogonResult* msg);
  static void set_has_text_message(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& server_utc_timestamp(const AccountLogonResult* msg);
  static void set_has_server_utc_timestamp(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000000e) ^ 0x0000000e) != 0;
  }
};

const ::shared_1::Text&
AccountLogonResult::_Internal::text_message(const AccountLogonResult* msg) {
  return *msg->_impl_.text_message_;
}
const ::PROTOBUF_NAMESPACE_ID::Timestamp&
AccountLogonResult::_Internal::server_utc_timestamp(const AccountLogonResult* msg) {
  return *msg->_impl_.server_utc_timestamp_;
}
void AccountLogonResult::clear_text_message() {
  if (_impl_.text_message_ != nullptr) _impl_.text_message_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void AccountLogonResult::clear_server_utc_timestamp() {
  if (_impl_.server_utc_timestamp_ != nullptr) _impl_.server_utc_timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
AccountLogonResult::AccountLogonResult(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:account_authorization_2.AccountLogonResult)
}
AccountLogonResult::AccountLogonResult(const AccountLogonResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AccountLogonResult* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.text_message_){nullptr}
    , decltype(_impl_.server_utc_timestamp_){nullptr}
    , decltype(_impl_.account_id_) {}

    , decltype(_impl_.result_code_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.text_message_ = new ::shared_1::Text(*from._impl_.text_message_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.server_utc_timestamp_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.server_utc_timestamp_);
  }
  ::memcpy(&_impl_.account_id_, &from._impl_.account_id_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.result_code_) -
    reinterpret_cast<char*>(&_impl_.account_id_)) + sizeof(_impl_.result_code_));
  // @@protoc_insertion_point(copy_constructor:account_authorization_2.AccountLogonResult)
}

inline void AccountLogonResult::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.text_message_){nullptr}
    , decltype(_impl_.server_utc_timestamp_){nullptr}
    , decltype(_impl_.account_id_) { 0 }

    , decltype(_impl_.result_code_) { 0u }

  };
}

AccountLogonResult::~AccountLogonResult() {
  // @@protoc_insertion_point(destructor:account_authorization_2.AccountLogonResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AccountLogonResult::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.text_message_;
  if (this != internal_default_instance()) delete _impl_.server_utc_timestamp_;
}

void AccountLogonResult::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AccountLogonResult::Clear() {
// @@protoc_insertion_point(message_clear_start:account_authorization_2.AccountLogonResult)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.text_message_ != nullptr);
      _impl_.text_message_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.server_utc_timestamp_ != nullptr);
      _impl_.server_utc_timestamp_->Clear();
    }
  }
  if (cached_has_bits & 0x0000000cu) {
    ::memset(&_impl_.account_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.result_code_) -
        reinterpret_cast<char*>(&_impl_.account_id_)) + sizeof(_impl_.result_code_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AccountLogonResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required sint32 account_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_account_id(&has_bits);
          _impl_.account_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // required uint32 result_code = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _Internal::set_has_result_code(&has_bits);
          _impl_.result_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional .shared_1.Text text_message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_text_message(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // required .google.protobuf.Timestamp server_utc_timestamp = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_server_utc_timestamp(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* AccountLogonResult::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:account_authorization_2.AccountLogonResult)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required sint32 account_id = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
        1, this->_internal_account_id(), target);
  }

  // required uint32 result_code = 2;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_result_code(), target);
  }

  // optional .shared_1.Text text_message = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::text_message(this),
        _Internal::text_message(this).GetCachedSize(), target, stream);
  }

  // required .google.protobuf.Timestamp server_utc_timestamp = 4;
  if (cached_has_bits & 0x00000002u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::server_utc_timestamp(this),
        _Internal::server_utc_timestamp(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:account_authorization_2.AccountLogonResult)
  return target;
}

::size_t AccountLogonResult::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:account_authorization_2.AccountLogonResult)
  ::size_t total_size = 0;

  if ((_impl_._has_bits_[0] & 0x00000002u) != 0) {
    // required .google.protobuf.Timestamp server_utc_timestamp = 4;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.server_utc_timestamp_);
  }

  if ((_impl_._has_bits_[0] & 0x00000004u) != 0) {
    // required sint32 account_id = 1;
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
        this->_internal_account_id());
  }

  if ((_impl_._has_bits_[0] & 0x00000008u) != 0) {
    // required uint32 result_code = 2;
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_result_code());
  }

  return total_size;
}
::size_t AccountLogonResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:account_authorization_2.AccountLogonResult)
  ::size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x0000000e) ^ 0x0000000e) == 0) {  // All required fields are present.
    // required .google.protobuf.Timestamp server_utc_timestamp = 4;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.server_utc_timestamp_);

    // required sint32 account_id = 1;
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
        this->_internal_account_id());

    // required uint32 result_code = 2;
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_result_code());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .shared_1.Text text_message = 3;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.text_message_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AccountLogonResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AccountLogonResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AccountLogonResult::GetClassData() const { return &_class_data_; }


void AccountLogonResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AccountLogonResult*>(&to_msg);
  auto& from = static_cast<const AccountLogonResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:account_authorization_2.AccountLogonResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_text_message()->::shared_1::Text::MergeFrom(
          from._internal_text_message());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_server_utc_timestamp()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
          from._internal_server_utc_timestamp());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.account_id_ = from._impl_.account_id_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.result_code_ = from._impl_.result_code_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AccountLogonResult::CopyFrom(const AccountLogonResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:account_authorization_2.AccountLogonResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AccountLogonResult::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  if ((_impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!_impl_.text_message_->IsInitialized()) return false;
  }
  return true;
}

void AccountLogonResult::InternalSwap(AccountLogonResult* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AccountLogonResult, _impl_.result_code_)
      + sizeof(AccountLogonResult::_impl_.result_code_)
      - PROTOBUF_FIELD_OFFSET(AccountLogonResult, _impl_.text_message_)>(
          reinterpret_cast<char*>(&_impl_.text_message_),
          reinterpret_cast<char*>(&other->_impl_.text_message_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AccountLogonResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_account_5fauthorization_5f2_2eproto_getter, &descriptor_table_account_5fauthorization_5f2_2eproto_once,
      file_level_metadata_account_5fauthorization_5f2_2eproto[1]);
}
// ===================================================================

class AccountPasswordChange::_Internal {
 public:
  using HasBits = decltype(std::declval<AccountPasswordChange>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AccountPasswordChange, _impl_._has_bits_);
  static void set_has_account_id(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_old_password(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_new_password(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

AccountPasswordChange::AccountPasswordChange(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:account_authorization_2.AccountPasswordChange)
}
AccountPasswordChange::AccountPasswordChange(const AccountPasswordChange& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AccountPasswordChange* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.old_password_) {}

    , decltype(_impl_.new_password_) {}

    , decltype(_impl_.account_id_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.old_password_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.old_password_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.old_password_.Set(from._internal_old_password(), _this->GetArenaForAllocation());
  }
  _impl_.new_password_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.new_password_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.new_password_.Set(from._internal_new_password(), _this->GetArenaForAllocation());
  }
  _this->_impl_.account_id_ = from._impl_.account_id_;
  // @@protoc_insertion_point(copy_constructor:account_authorization_2.AccountPasswordChange)
}

inline void AccountPasswordChange::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.old_password_) {}

    , decltype(_impl_.new_password_) {}

    , decltype(_impl_.account_id_) { 0 }

  };
  _impl_.old_password_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.old_password_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.new_password_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.new_password_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AccountPasswordChange::~AccountPasswordChange() {
  // @@protoc_insertion_point(destructor:account_authorization_2.AccountPasswordChange)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AccountPasswordChange::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.old_password_.Destroy();
  _impl_.new_password_.Destroy();
}

void AccountPasswordChange::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AccountPasswordChange::Clear() {
// @@protoc_insertion_point(message_clear_start:account_authorization_2.AccountPasswordChange)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.old_password_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.new_password_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.account_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AccountPasswordChange::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required sint32 account_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_account_id(&has_bits);
          _impl_.account_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // required string old_password = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_old_password();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "account_authorization_2.AccountPasswordChange.old_password");
          #endif  // !NDEBUG
        } else {
          goto handle_unusual;
        }
        continue;
      // required string new_password = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_new_password();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "account_authorization_2.AccountPasswordChange.new_password");
          #endif  // !NDEBUG
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* AccountPasswordChange::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:account_authorization_2.AccountPasswordChange)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required sint32 account_id = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
        1, this->_internal_account_id(), target);
  }

  // required string old_password = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_old_password();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
                                "account_authorization_2.AccountPasswordChange.old_password");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // required string new_password = 3;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_new_password();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
                                "account_authorization_2.AccountPasswordChange.new_password");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:account_authorization_2.AccountPasswordChange)
  return target;
}

::size_t AccountPasswordChange::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:account_authorization_2.AccountPasswordChange)
  ::size_t total_size = 0;

  if ((_impl_._has_bits_[0] & 0x00000001u) != 0) {
    // required string old_password = 2;
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_old_password());
  }

  if ((_impl_._has_bits_[0] & 0x00000002u) != 0) {
    // required string new_password = 3;
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_new_password());
  }

  if ((_impl_._has_bits_[0] & 0x00000004u) != 0) {
    // required sint32 account_id = 1;
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
        this->_internal_account_id());
  }

  return total_size;
}
::size_t AccountPasswordChange::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:account_authorization_2.AccountPasswordChange)
  ::size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string old_password = 2;
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_old_password());

    // required string new_password = 3;
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_new_password());

    // required sint32 account_id = 1;
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
        this->_internal_account_id());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AccountPasswordChange::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AccountPasswordChange::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AccountPasswordChange::GetClassData() const { return &_class_data_; }


void AccountPasswordChange::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AccountPasswordChange*>(&to_msg);
  auto& from = static_cast<const AccountPasswordChange&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:account_authorization_2.AccountPasswordChange)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_old_password(from._internal_old_password());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_new_password(from._internal_new_password());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.account_id_ = from._impl_.account_id_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AccountPasswordChange::CopyFrom(const AccountPasswordChange& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:account_authorization_2.AccountPasswordChange)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AccountPasswordChange::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void AccountPasswordChange::InternalSwap(AccountPasswordChange* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.old_password_, lhs_arena,
                                       &other->_impl_.old_password_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.new_password_, lhs_arena,
                                       &other->_impl_.new_password_, rhs_arena);

  swap(_impl_.account_id_, other->_impl_.account_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AccountPasswordChange::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_account_5fauthorization_5f2_2eproto_getter, &descriptor_table_account_5fauthorization_5f2_2eproto_once,
      file_level_metadata_account_5fauthorization_5f2_2eproto[2]);
}
// ===================================================================

class AccountPasswordChangeResult::_Internal {
 public:
  using HasBits = decltype(std::declval<AccountPasswordChangeResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AccountPasswordChangeResult, _impl_._has_bits_);
  static void set_has_account_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_result_code(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::shared_1::Text& text_message(const AccountPasswordChangeResult* msg);
  static void set_has_text_message(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000006) ^ 0x00000006) != 0;
  }
};

const ::shared_1::Text&
AccountPasswordChangeResult::_Internal::text_message(const AccountPasswordChangeResult* msg) {
  return *msg->_impl_.text_message_;
}
void AccountPasswordChangeResult::clear_text_message() {
  if (_impl_.text_message_ != nullptr) _impl_.text_message_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
AccountPasswordChangeResult::AccountPasswordChangeResult(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:account_authorization_2.AccountPasswordChangeResult)
}
AccountPasswordChangeResult::AccountPasswordChangeResult(const AccountPasswordChangeResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AccountPasswordChangeResult* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.text_message_){nullptr}
    , decltype(_impl_.account_id_) {}

    , decltype(_impl_.result_code_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.text_message_ = new ::shared_1::Text(*from._impl_.text_message_);
  }
  ::memcpy(&_impl_.account_id_, &from._impl_.account_id_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.result_code_) -
    reinterpret_cast<char*>(&_impl_.account_id_)) + sizeof(_impl_.result_code_));
  // @@protoc_insertion_point(copy_constructor:account_authorization_2.AccountPasswordChangeResult)
}

inline void AccountPasswordChangeResult::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.text_message_){nullptr}
    , decltype(_impl_.account_id_) { 0 }

    , decltype(_impl_.result_code_) { 0u }

  };
}

AccountPasswordChangeResult::~AccountPasswordChangeResult() {
  // @@protoc_insertion_point(destructor:account_authorization_2.AccountPasswordChangeResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AccountPasswordChangeResult::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.text_message_;
}

void AccountPasswordChangeResult::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AccountPasswordChangeResult::Clear() {
// @@protoc_insertion_point(message_clear_start:account_authorization_2.AccountPasswordChangeResult)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.text_message_ != nullptr);
    _impl_.text_message_->Clear();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.account_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.result_code_) -
        reinterpret_cast<char*>(&_impl_.account_id_)) + sizeof(_impl_.result_code_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AccountPasswordChangeResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required sint32 account_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_account_id(&has_bits);
          _impl_.account_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // required uint32 result_code = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _Internal::set_has_result_code(&has_bits);
          _impl_.result_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional .shared_1.Text text_message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_text_message(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* AccountPasswordChangeResult::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:account_authorization_2.AccountPasswordChangeResult)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required sint32 account_id = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
        1, this->_internal_account_id(), target);
  }

  // required uint32 result_code = 2;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_result_code(), target);
  }

  // optional .shared_1.Text text_message = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::text_message(this),
        _Internal::text_message(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:account_authorization_2.AccountPasswordChangeResult)
  return target;
}

::size_t AccountPasswordChangeResult::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:account_authorization_2.AccountPasswordChangeResult)
  ::size_t total_size = 0;

  if ((_impl_._has_bits_[0] & 0x00000002u) != 0) {
    // required sint32 account_id = 1;
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
        this->_internal_account_id());
  }

  if ((_impl_._has_bits_[0] & 0x00000004u) != 0) {
    // required uint32 result_code = 2;
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_result_code());
  }

  return total_size;
}
::size_t AccountPasswordChangeResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:account_authorization_2.AccountPasswordChangeResult)
  ::size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x00000006) ^ 0x00000006) == 0) {  // All required fields are present.
    // required sint32 account_id = 1;
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
        this->_internal_account_id());

    // required uint32 result_code = 2;
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_result_code());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .shared_1.Text text_message = 3;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.text_message_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AccountPasswordChangeResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AccountPasswordChangeResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AccountPasswordChangeResult::GetClassData() const { return &_class_data_; }


void AccountPasswordChangeResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AccountPasswordChangeResult*>(&to_msg);
  auto& from = static_cast<const AccountPasswordChangeResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:account_authorization_2.AccountPasswordChangeResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_text_message()->::shared_1::Text::MergeFrom(
          from._internal_text_message());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.account_id_ = from._impl_.account_id_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.result_code_ = from._impl_.result_code_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AccountPasswordChangeResult::CopyFrom(const AccountPasswordChangeResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:account_authorization_2.AccountPasswordChangeResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AccountPasswordChangeResult::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  if ((_impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!_impl_.text_message_->IsInitialized()) return false;
  }
  return true;
}

void AccountPasswordChangeResult::InternalSwap(AccountPasswordChangeResult* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AccountPasswordChangeResult, _impl_.result_code_)
      + sizeof(AccountPasswordChangeResult::_impl_.result_code_)
      - PROTOBUF_FIELD_OFFSET(AccountPasswordChangeResult, _impl_.text_message_)>(
          reinterpret_cast<char*>(&_impl_.text_message_),
          reinterpret_cast<char*>(&other->_impl_.text_message_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AccountPasswordChangeResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_account_5fauthorization_5f2_2eproto_getter, &descriptor_table_account_5fauthorization_5f2_2eproto_once,
      file_level_metadata_account_5fauthorization_5f2_2eproto[3]);
}
// ===================================================================

class AccountLogoff::_Internal {
 public:
  using HasBits = decltype(std::declval<AccountLogoff>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AccountLogoff, _impl_._has_bits_);
  static void set_has_account_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

AccountLogoff::AccountLogoff(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:account_authorization_2.AccountLogoff)
}
AccountLogoff::AccountLogoff(const AccountLogoff& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:account_authorization_2.AccountLogoff)
}

inline void AccountLogoff::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.account_id_) { 0 }

  };
}

AccountLogoff::~AccountLogoff() {
  // @@protoc_insertion_point(destructor:account_authorization_2.AccountLogoff)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AccountLogoff::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void AccountLogoff::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AccountLogoff::Clear() {
// @@protoc_insertion_point(message_clear_start:account_authorization_2.AccountLogoff)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.account_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AccountLogoff::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required sint32 account_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_account_id(&has_bits);
          _impl_.account_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* AccountLogoff::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:account_authorization_2.AccountLogoff)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required sint32 account_id = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
        1, this->_internal_account_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:account_authorization_2.AccountLogoff)
  return target;
}

::size_t AccountLogoff::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:account_authorization_2.AccountLogoff)
  ::size_t total_size = 0;

  // required sint32 account_id = 1;
  if ((_impl_._has_bits_[0] & 0x00000001u) != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
        this->_internal_account_id());
  }
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AccountLogoff::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AccountLogoff::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AccountLogoff::GetClassData() const { return &_class_data_; }


void AccountLogoff::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AccountLogoff*>(&to_msg);
  auto& from = static_cast<const AccountLogoff&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:account_authorization_2.AccountLogoff)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_account_id(from._internal_account_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AccountLogoff::CopyFrom(const AccountLogoff& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:account_authorization_2.AccountLogoff)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AccountLogoff::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void AccountLogoff::InternalSwap(AccountLogoff* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);

  swap(_impl_.account_id_, other->_impl_.account_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AccountLogoff::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_account_5fauthorization_5f2_2eproto_getter, &descriptor_table_account_5fauthorization_5f2_2eproto_once,
      file_level_metadata_account_5fauthorization_5f2_2eproto[4]);
}
// ===================================================================

class AccountLogoffResult::_Internal {
 public:
  using HasBits = decltype(std::declval<AccountLogoffResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AccountLogoffResult, _impl_._has_bits_);
  static void set_has_account_id(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_result_code(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static const ::shared_1::Text& text_message(const AccountLogoffResult* msg);
  static void set_has_text_message(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& server_utc_timestamp(const AccountLogoffResult* msg);
  static void set_has_server_utc_timestamp(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000000e) ^ 0x0000000e) != 0;
  }
};

const ::shared_1::Text&
AccountLogoffResult::_Internal::text_message(const AccountLogoffResult* msg) {
  return *msg->_impl_.text_message_;
}
const ::PROTOBUF_NAMESPACE_ID::Timestamp&
AccountLogoffResult::_Internal::server_utc_timestamp(const AccountLogoffResult* msg) {
  return *msg->_impl_.server_utc_timestamp_;
}
void AccountLogoffResult::clear_text_message() {
  if (_impl_.text_message_ != nullptr) _impl_.text_message_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void AccountLogoffResult::clear_server_utc_timestamp() {
  if (_impl_.server_utc_timestamp_ != nullptr) _impl_.server_utc_timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
AccountLogoffResult::AccountLogoffResult(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:account_authorization_2.AccountLogoffResult)
}
AccountLogoffResult::AccountLogoffResult(const AccountLogoffResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AccountLogoffResult* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.text_message_){nullptr}
    , decltype(_impl_.server_utc_timestamp_){nullptr}
    , decltype(_impl_.account_id_) {}

    , decltype(_impl_.result_code_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.text_message_ = new ::shared_1::Text(*from._impl_.text_message_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.server_utc_timestamp_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.server_utc_timestamp_);
  }
  ::memcpy(&_impl_.account_id_, &from._impl_.account_id_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.result_code_) -
    reinterpret_cast<char*>(&_impl_.account_id_)) + sizeof(_impl_.result_code_));
  // @@protoc_insertion_point(copy_constructor:account_authorization_2.AccountLogoffResult)
}

inline void AccountLogoffResult::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.text_message_){nullptr}
    , decltype(_impl_.server_utc_timestamp_){nullptr}
    , decltype(_impl_.account_id_) { 0 }

    , decltype(_impl_.result_code_) { 0u }

  };
}

AccountLogoffResult::~AccountLogoffResult() {
  // @@protoc_insertion_point(destructor:account_authorization_2.AccountLogoffResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AccountLogoffResult::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.text_message_;
  if (this != internal_default_instance()) delete _impl_.server_utc_timestamp_;
}

void AccountLogoffResult::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AccountLogoffResult::Clear() {
// @@protoc_insertion_point(message_clear_start:account_authorization_2.AccountLogoffResult)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.text_message_ != nullptr);
      _impl_.text_message_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.server_utc_timestamp_ != nullptr);
      _impl_.server_utc_timestamp_->Clear();
    }
  }
  if (cached_has_bits & 0x0000000cu) {
    ::memset(&_impl_.account_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.result_code_) -
        reinterpret_cast<char*>(&_impl_.account_id_)) + sizeof(_impl_.result_code_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AccountLogoffResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required sint32 account_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_account_id(&has_bits);
          _impl_.account_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // required uint32 result_code = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _Internal::set_has_result_code(&has_bits);
          _impl_.result_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional .shared_1.Text text_message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_text_message(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // required .google.protobuf.Timestamp server_utc_timestamp = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_server_utc_timestamp(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* AccountLogoffResult::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:account_authorization_2.AccountLogoffResult)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required sint32 account_id = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
        1, this->_internal_account_id(), target);
  }

  // required uint32 result_code = 2;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_result_code(), target);
  }

  // optional .shared_1.Text text_message = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::text_message(this),
        _Internal::text_message(this).GetCachedSize(), target, stream);
  }

  // required .google.protobuf.Timestamp server_utc_timestamp = 4;
  if (cached_has_bits & 0x00000002u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::server_utc_timestamp(this),
        _Internal::server_utc_timestamp(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:account_authorization_2.AccountLogoffResult)
  return target;
}

::size_t AccountLogoffResult::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:account_authorization_2.AccountLogoffResult)
  ::size_t total_size = 0;

  if ((_impl_._has_bits_[0] & 0x00000002u) != 0) {
    // required .google.protobuf.Timestamp server_utc_timestamp = 4;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.server_utc_timestamp_);
  }

  if ((_impl_._has_bits_[0] & 0x00000004u) != 0) {
    // required sint32 account_id = 1;
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
        this->_internal_account_id());
  }

  if ((_impl_._has_bits_[0] & 0x00000008u) != 0) {
    // required uint32 result_code = 2;
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_result_code());
  }

  return total_size;
}
::size_t AccountLogoffResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:account_authorization_2.AccountLogoffResult)
  ::size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x0000000e) ^ 0x0000000e) == 0) {  // All required fields are present.
    // required .google.protobuf.Timestamp server_utc_timestamp = 4;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.server_utc_timestamp_);

    // required sint32 account_id = 1;
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
        this->_internal_account_id());

    // required uint32 result_code = 2;
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_result_code());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .shared_1.Text text_message = 3;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.text_message_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AccountLogoffResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AccountLogoffResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AccountLogoffResult::GetClassData() const { return &_class_data_; }


void AccountLogoffResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AccountLogoffResult*>(&to_msg);
  auto& from = static_cast<const AccountLogoffResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:account_authorization_2.AccountLogoffResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_text_message()->::shared_1::Text::MergeFrom(
          from._internal_text_message());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_server_utc_timestamp()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
          from._internal_server_utc_timestamp());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.account_id_ = from._impl_.account_id_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.result_code_ = from._impl_.result_code_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AccountLogoffResult::CopyFrom(const AccountLogoffResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:account_authorization_2.AccountLogoffResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AccountLogoffResult::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  if ((_impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!_impl_.text_message_->IsInitialized()) return false;
  }
  return true;
}

void AccountLogoffResult::InternalSwap(AccountLogoffResult* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AccountLogoffResult, _impl_.result_code_)
      + sizeof(AccountLogoffResult::_impl_.result_code_)
      - PROTOBUF_FIELD_OFFSET(AccountLogoffResult, _impl_.text_message_)>(
          reinterpret_cast<char*>(&_impl_.text_message_),
          reinterpret_cast<char*>(&other->_impl_.text_message_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AccountLogoffResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_account_5fauthorization_5f2_2eproto_getter, &descriptor_table_account_5fauthorization_5f2_2eproto_once,
      file_level_metadata_account_5fauthorization_5f2_2eproto[5]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace account_authorization_2
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::account_authorization_2::AccountLogon*
Arena::CreateMaybeMessage< ::account_authorization_2::AccountLogon >(Arena* arena) {
  return Arena::CreateMessageInternal< ::account_authorization_2::AccountLogon >(arena);
}
template<> PROTOBUF_NOINLINE ::account_authorization_2::AccountLogonResult*
Arena::CreateMaybeMessage< ::account_authorization_2::AccountLogonResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::account_authorization_2::AccountLogonResult >(arena);
}
template<> PROTOBUF_NOINLINE ::account_authorization_2::AccountPasswordChange*
Arena::CreateMaybeMessage< ::account_authorization_2::AccountPasswordChange >(Arena* arena) {
  return Arena::CreateMessageInternal< ::account_authorization_2::AccountPasswordChange >(arena);
}
template<> PROTOBUF_NOINLINE ::account_authorization_2::AccountPasswordChangeResult*
Arena::CreateMaybeMessage< ::account_authorization_2::AccountPasswordChangeResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::account_authorization_2::AccountPasswordChangeResult >(arena);
}
template<> PROTOBUF_NOINLINE ::account_authorization_2::AccountLogoff*
Arena::CreateMaybeMessage< ::account_authorization_2::AccountLogoff >(Arena* arena) {
  return Arena::CreateMessageInternal< ::account_authorization_2::AccountLogoff >(arena);
}
template<> PROTOBUF_NOINLINE ::account_authorization_2::AccountLogoffResult*
Arena::CreateMaybeMessage< ::account_authorization_2::AccountLogoffResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::account_authorization_2::AccountLogoffResult >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
